services:
  mongodb_sync:
    image: olakego/source-mongodb:latest
    command: >
      sync
      --config /mnt/config/config.json
      --catalog /mnt/config/catalog.json
      --destination /mnt/config/writer.json
      --state /mnt/config/state.json
    volumes:
      - ./drivers/mongodb/examples:/mnt/config

  mysql:
    image: mysql:8.0
    command:
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --binlog-row-metadata=FULL
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
