package testutils

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"slices"
	"testing"

	"github.com/datazip-inc/olake/constants"
	"github.com/datazip-inc/olake/utils"
	"github.com/minio/minio-go/v7"
	pqgo "github.com/parquet-go/parquet-go"
	"github.com/stretchr/testify/require"
	"github.com/testcontainers/testcontainers-go"
)

const (
	// RollingSeedRows is the number of rows the rolling test seeds. With ~100 bytes of
	// incompressible parquet per row this is ~8MB — several times the 1MB roll threshold,
	// so the writer is forced to roll into a handful of files. Shared with the driver's
	// "rolling_seed" ExecuteQuery case so the assertion and the seed stay in lock-step.
	RollingSeedRows = 50000
	// rollingMaxFileBytes must match "max_file_size_mb" in the driver's
	// parquet_destination.json (1 MB).
	rollingMaxFileBytes = 1 * 1024 * 1024
)

// parquetRollingTestDrivers lists the drivers wired for the Parquet Rolling sub-test inside the
// common Sync flow. Enabling another driver is a three-step checklist: append it here, add a
// "rolling_seed" case to that driver's ExecuteQuery, and set "max_file_size_mb" in that driver's
// parquet_destination.json.
var parquetRollingTestDrivers = []constants.DriverType{constants.Postgres}

// hasParquetRollingTest reports whether the driver participates in the Parquet Rolling sub-test.
func hasParquetRollingTest(driver string) bool {
	return slices.Contains(parquetRollingTestDrivers, constants.DriverType(driver))
}

// testParquetRolling exercises the parquet writer's memory/size-based file rolling against a
// real S3 (MinIO) destination. It runs as the last sub-test of the common Sync flow and reuses
// that flow's container, table and catalog: it bulk-seeds the table, re-syncs it to parquet, and
// asserts the writer split the output into multiple size-bounded files without losing rows.
//
// The seeded data (~8MB) is far smaller than the backfill chunk size (EffectiveParquetSize,
// 2GB), so the whole table is one chunk handled by one writer — meaning multiple bounded
// files can only come from rolling, not from chunk fan-out.
func (cfg *IntegrationTest) testParquetRolling(ctx context.Context, t *testing.T, c testcontainers.Container, testTable string) error {
	// Rolling needs the whole table to land in a single writer, so drop the partition regex
	// (identity partitioning would fan the rows out into a file per value) and the filter config
	// (the bulk rows are not shaped to satisfy it). Normalization stays on, as in the rest of the
	// Sync flow. Safe to leave patched: this is the flow's last sub-test and streams.json is
	// regenerated by Discover on every run.
	streamUpdateCmd := updateSelectedStreamsCommand(*cfg.TestConfig, cfg.Namespace, "", "", []string{testTable}, true, cfg.ColumnToExclude)
	if code, out, err := utils.ExecCommand(ctx, c, streamUpdateCmd); err != nil || code != 0 {
		return fmt.Errorf("failed to clear partition regex and filter config in streams.json (%d): %v\n%s", code, err, out)
	}

	// Swap the handful of datatype rows for a bulk payload.
	cfg.ExecuteQuery(ctx, t, []string{testTable}, "clean", false)
	cfg.ExecuteQuery(ctx, t, []string{testTable}, "rolling_seed", false)

	// Start from an empty destination folder — the earlier parquet sub-tests leave files and
	// destination metadata behind, while this is an independent initial sync.
	if err := deleteParquetTable(t, cfg.DestinationDB, testTable); err != nil {
		return fmt.Errorf("failed to reset parquet table before rolling sync: %s", err)
	}
	defer func() {
		if err := deleteParquetTable(t, cfg.DestinationDB, testTable); err != nil {
			t.Logf("cleanup: failed to reset parquet table: %v", err)
		}
	}()

	// Full load (no --state) with a small buffer so rolled files hug the threshold.
	syncCmd := syncCommand(*cfg.TestConfig, false, "parquet")
	if code, out, err := utils.ExecCommand(ctx, c, syncCmd); err != nil || code != 0 {
		return fmt.Errorf("rolling sync failed (%d): %v\n%s", code, err, out)
	}

	cfg.verifyParquetRolling(t, testTable)
	return nil
}

// verifyParquetRolling reads the rolled objects from MinIO and asserts the writer
// (1) produced multiple files, (2) bounded every file near the roll threshold (the core
// proof — a broken roll would leave one oversized file), and (3) preserved every row.
func (cfg *IntegrationTest) verifyParquetRolling(t *testing.T, table string) {
	t.Helper()
	ctx := context.Background()

	client, err := newMinIOClient()
	require.NoError(t, err)

	objects, err := listParquetObjects(ctx, client, cfg.DestinationDB, table)
	require.NoError(t, err, "failed to list rolled parquet files")

	var totalSize int64
	for _, obj := range objects {
		require.LessOrEqualf(t, obj.Size, int64(2*rollingMaxFileBytes),
			"file %s is %d bytes, exceeding 2x the roll threshold — rolling did not bound file size", obj.Key, obj.Size)
		totalSize += obj.Size
	}

	require.GreaterOrEqualf(t, len(objects), 2,
		"expected the writer to roll into multiple parquet files for table %s, got %d", table, len(objects))
	require.Greaterf(t, totalSize, int64(4*rollingMaxFileBytes),
		"total parquet size %d is too small to meaningfully exercise rolling", totalSize)

	// Sum footer row counts across every rolled file — no rows may be lost at a roll boundary.
	var totalRows int64
	for _, obj := range objects {
		reader, gerr := client.GetObject(ctx, parquetTestBucket, obj.Key, minio.GetObjectOptions{})
		require.NoErrorf(t, gerr, "failed to get object %s", obj.Key)
		data, rerr := io.ReadAll(reader)
		_ = reader.Close()
		require.NoErrorf(t, rerr, "failed to read object %s", obj.Key)
		pf, oerr := pqgo.OpenFile(bytes.NewReader(data), int64(len(data)))
		require.NoErrorf(t, oerr, "failed to open parquet %s", obj.Key)
		totalRows += pf.NumRows()
	}
	require.Equalf(t, int64(RollingSeedRows), totalRows, "row count mismatch across rolled files")

	t.Logf("parquet rolling OK: %d files, %d bytes total, %d rows (threshold %d bytes)",
		len(objects), totalSize, totalRows, rollingMaxFileBytes)
}
