// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: records_ingest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriterMode int32

const (
	WriterMode_LEGACY WriterMode = 0
	WriterMode_ARROW  WriterMode = 1
)

// Enum value maps for WriterMode.
var (
	WriterMode_name = map[int32]string{
		0: "LEGACY",
		1: "ARROW",
	}
	WriterMode_value = map[string]int32{
		"LEGACY": 0,
		"ARROW":  1,
	}
)

func (x WriterMode) Enum() *WriterMode {
	p := new(WriterMode)
	*p = x
	return p
}

func (x WriterMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriterMode) Descriptor() protoreflect.EnumDescriptor {
	return file_records_ingest_proto_enumTypes[0].Descriptor()
}

func (WriterMode) Type() protoreflect.EnumType {
	return &file_records_ingest_proto_enumTypes[0]
}

func (x WriterMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriterMode.Descriptor instead.
func (WriterMode) EnumDescriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0}
}

// ============================================
// Core Shared Messages
// ============================================
type SchemaField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IceType       string                 `protobuf:"bytes,1,opt,name=ice_type,json=iceType,proto3" json:"ice_type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaField) Reset() {
	*x = SchemaField{}
	mi := &file_records_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaField) ProtoMessage() {}

func (x *SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaField.ProtoReflect.Descriptor instead.
func (*SchemaField) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaField) GetIceType() string {
	if x != nil {
		return x.IceType
	}
	return ""
}

func (x *SchemaField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PartitionField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Transform     string                 `protobuf:"bytes,2,opt,name=transform,proto3" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionField) Reset() {
	*x = PartitionField{}
	mi := &file_records_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionField) ProtoMessage() {}

func (x *PartitionField) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionField.ProtoReflect.Descriptor instead.
func (*PartitionField) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *PartitionField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *PartitionField) GetTransform() string {
	if x != nil {
		return x.Transform
	}
	return ""
}

type TableConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DestTableName string                 `protobuf:"bytes,1,opt,name=dest_table_name,json=destTableName,proto3" json:"dest_table_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Upsert        bool                   `protobuf:"varint,3,opt,name=upsert,proto3" json:"upsert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableConfig) Reset() {
	*x = TableConfig{}
	mi := &file_records_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableConfig) ProtoMessage() {}

func (x *TableConfig) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableConfig.ProtoReflect.Descriptor instead.
func (*TableConfig) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *TableConfig) GetDestTableName() string {
	if x != nil {
		return x.DestTableName
	}
	return ""
}

func (x *TableConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TableConfig) GetUpsert() bool {
	if x != nil {
		return x.Upsert
	}
	return false
}

type CheckConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TableName     string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConnectionRequest) Reset() {
	*x = CheckConnectionRequest{}
	mi := &file_records_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConnectionRequest) ProtoMessage() {}

func (x *CheckConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConnectionRequest.ProtoReflect.Descriptor instead.
func (*CheckConnectionRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *CheckConnectionRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CheckConnectionRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type CheckConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConnectionResponse) Reset() {
	*x = CheckConnectionResponse{}
	mi := &file_records_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConnectionResponse) ProtoMessage() {}

func (x *CheckConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConnectionResponse.ProtoReflect.Descriptor instead.
func (*CheckConnectionResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *CheckConnectionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DropTablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []string               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"` // "namespace.table"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropTablesRequest) Reset() {
	*x = DropTablesRequest{}
	mi := &file_records_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTablesRequest) ProtoMessage() {}

func (x *DropTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTablesRequest.ProtoReflect.Descriptor instead.
func (*DropTablesRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *DropTablesRequest) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

type DropTablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropTablesResponse) Reset() {
	*x = DropTablesResponse{}
	mi := &file_records_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTablesResponse) ProtoMessage() {}

func (x *DropTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTablesResponse.ProtoReflect.Descriptor instead.
func (*DropTablesResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{6}
}

func (x *DropTablesResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type InitSessionRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ThreadId    string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	TableConfig *TableConfig           `protobuf:"bytes,2,opt,name=table_config,json=tableConfig,proto3" json:"table_config,omitempty"`
	Mode        WriterMode             `protobuf:"varint,3,opt,name=mode,proto3,enum=io.olake.server.iceberg.rpc.WriterMode" json:"mode,omitempty"`
	// Legacy writer: schema + partition spec. Identifier field (_olake_id) is set on the
	// JVM when table_config.upsert is true; append mode creates tables without identifiers.
	Schema          []*SchemaField    `protobuf:"bytes,4,rep,name=schema,proto3" json:"schema,omitempty"`
	PartitionFields []*PartitionField `protobuf:"bytes,5,rep,name=partition_fields,json=partitionFields,proto3" json:"partition_fields,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitSessionRequest) Reset() {
	*x = InitSessionRequest{}
	mi := &file_records_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSessionRequest) ProtoMessage() {}

func (x *InitSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSessionRequest.ProtoReflect.Descriptor instead.
func (*InitSessionRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{7}
}

func (x *InitSessionRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *InitSessionRequest) GetTableConfig() *TableConfig {
	if x != nil {
		return x.TableConfig
	}
	return nil
}

func (x *InitSessionRequest) GetMode() WriterMode {
	if x != nil {
		return x.Mode
	}
	return WriterMode_LEGACY
}

func (x *InitSessionRequest) GetSchema() []*SchemaField {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *InitSessionRequest) GetPartitionFields() []*PartitionField {
	if x != nil {
		return x.PartitionFields
	}
	return nil
}

type InitSessionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Result         string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Olake_2PcState string                 `protobuf:"bytes,2,opt,name=olake_2pc_state,json=olake2pcState,proto3" json:"olake_2pc_state,omitempty"`                                                      // For row
	SchemaJson     string                 `protobuf:"bytes,3,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`                                                                 // For row
	IcebergSchemas map[string]string      `protobuf:"bytes,4,rep,name=icebergSchemas,proto3" json:"icebergSchemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // For arrow
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitSessionResponse) Reset() {
	*x = InitSessionResponse{}
	mi := &file_records_ingest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSessionResponse) ProtoMessage() {}

func (x *InitSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSessionResponse.ProtoReflect.Descriptor instead.
func (*InitSessionResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{8}
}

func (x *InitSessionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *InitSessionResponse) GetOlake_2PcState() string {
	if x != nil {
		return x.Olake_2PcState
	}
	return ""
}

func (x *InitSessionResponse) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

func (x *InitSessionResponse) GetIcebergSchemas() map[string]string {
	if x != nil {
		return x.IcebergSchemas
	}
	return nil
}

type SendRecordsRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	ThreadId      string                          `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Schema        []*SchemaField                  `protobuf:"bytes,2,rep,name=schema,proto3" json:"schema,omitempty"`
	Records       []*SendRecordsRequest_IceRecord `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRecordsRequest) Reset() {
	*x = SendRecordsRequest{}
	mi := &file_records_ingest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRecordsRequest) ProtoMessage() {}

func (x *SendRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRecordsRequest.ProtoReflect.Descriptor instead.
func (*SendRecordsRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{9}
}

func (x *SendRecordsRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SendRecordsRequest) GetSchema() []*SchemaField {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *SendRecordsRequest) GetRecords() []*SendRecordsRequest_IceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type SendRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRecordsResponse) Reset() {
	*x = SendRecordsResponse{}
	mi := &file_records_ingest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRecordsResponse) ProtoMessage() {}

func (x *SendRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRecordsResponse.ProtoReflect.Descriptor instead.
func (*SendRecordsResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{10}
}

func (x *SendRecordsResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type EvolveSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Schema        []*SchemaField         `protobuf:"bytes,2,rep,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvolveSchemaRequest) Reset() {
	*x = EvolveSchemaRequest{}
	mi := &file_records_ingest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvolveSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolveSchemaRequest) ProtoMessage() {}

func (x *EvolveSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolveSchemaRequest.ProtoReflect.Descriptor instead.
func (*EvolveSchemaRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{11}
}

func (x *EvolveSchemaRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *EvolveSchemaRequest) GetSchema() []*SchemaField {
	if x != nil {
		return x.Schema
	}
	return nil
}

type EvolveSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	SchemaJson    string                 `protobuf:"bytes,2,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvolveSchemaResponse) Reset() {
	*x = EvolveSchemaResponse{}
	mi := &file_records_ingest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvolveSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolveSchemaResponse) ProtoMessage() {}

func (x *EvolveSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolveSchemaResponse.ProtoReflect.Descriptor instead.
func (*EvolveSchemaResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{12}
}

func (x *EvolveSchemaResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *EvolveSchemaResponse) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

type RefreshTableSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTableSchemaRequest) Reset() {
	*x = RefreshTableSchemaRequest{}
	mi := &file_records_ingest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTableSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTableSchemaRequest) ProtoMessage() {}

func (x *RefreshTableSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTableSchemaRequest.ProtoReflect.Descriptor instead.
func (*RefreshTableSchemaRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshTableSchemaRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type RefreshTableSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	SchemaJson    string                 `protobuf:"bytes,2,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTableSchemaResponse) Reset() {
	*x = RefreshTableSchemaResponse{}
	mi := &file_records_ingest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTableSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTableSchemaResponse) ProtoMessage() {}

func (x *RefreshTableSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTableSchemaResponse.ProtoReflect.Descriptor instead.
func (*RefreshTableSchemaResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{14}
}

func (x *RefreshTableSchemaResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RefreshTableSchemaResponse) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

type GetFilePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilePathRequest) Reset() {
	*x = GetFilePathRequest{}
	mi := &file_records_ingest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilePathRequest) ProtoMessage() {}

func (x *GetFilePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilePathRequest.ProtoReflect.Descriptor instead.
func (*GetFilePathRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{15}
}

func (x *GetFilePathRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type GetFilePathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilePathResponse) Reset() {
	*x = GetFilePathResponse{}
	mi := &file_records_ingest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilePathResponse) ProtoMessage() {}

func (x *GetFilePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilePathResponse.ProtoReflect.Descriptor instead.
func (*GetFilePathResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{16}
}

func (x *GetFilePathResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileData      []byte                 `protobuf:"bytes,3,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_records_ingest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{17}
}

func (x *UploadFileRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *UploadFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UploadFileRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_records_ingest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{18}
}

func (x *UploadFileResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CommitRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	ThreadId      string                        `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Payload       string                        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	FileMetadata  []*CommitRequest_FileMetadata `protobuf:"bytes,3,rep,name=file_metadata,json=fileMetadata,proto3" json:"file_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_records_ingest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{19}
}

func (x *CommitRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *CommitRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CommitRequest) GetFileMetadata() []*CommitRequest_FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_records_ingest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{20}
}

func (x *CommitResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_records_ingest_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{21}
}

func (x *CloseSessionRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_records_ingest_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{22}
}

func (x *CloseSessionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type SendRecordsRequest_FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*SendRecordsRequest_FieldValue_StringValue
	//	*SendRecordsRequest_FieldValue_IntValue
	//	*SendRecordsRequest_FieldValue_LongValue
	//	*SendRecordsRequest_FieldValue_FloatValue
	//	*SendRecordsRequest_FieldValue_DoubleValue
	//	*SendRecordsRequest_FieldValue_BoolValue
	//	*SendRecordsRequest_FieldValue_BytesValue
	Value         isSendRecordsRequest_FieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRecordsRequest_FieldValue) Reset() {
	*x = SendRecordsRequest_FieldValue{}
	mi := &file_records_ingest_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRecordsRequest_FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRecordsRequest_FieldValue) ProtoMessage() {}

func (x *SendRecordsRequest_FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRecordsRequest_FieldValue.ProtoReflect.Descriptor instead.
func (*SendRecordsRequest_FieldValue) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{9, 0}
}

func (x *SendRecordsRequest_FieldValue) GetValue() isSendRecordsRequest_FieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SendRecordsRequest_FieldValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*SendRecordsRequest_FieldValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *SendRecordsRequest_FieldValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*SendRecordsRequest_FieldValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *SendRecordsRequest_FieldValue) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*SendRecordsRequest_FieldValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *SendRecordsRequest_FieldValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*SendRecordsRequest_FieldValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *SendRecordsRequest_FieldValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*SendRecordsRequest_FieldValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *SendRecordsRequest_FieldValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*SendRecordsRequest_FieldValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *SendRecordsRequest_FieldValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*SendRecordsRequest_FieldValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isSendRecordsRequest_FieldValue_Value interface {
	isSendRecordsRequest_FieldValue_Value()
}

type SendRecordsRequest_FieldValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type SendRecordsRequest_FieldValue_IntValue struct {
	IntValue int32 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type SendRecordsRequest_FieldValue_LongValue struct {
	LongValue int64 `protobuf:"varint,3,opt,name=long_value,json=longValue,proto3,oneof"`
}

type SendRecordsRequest_FieldValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type SendRecordsRequest_FieldValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type SendRecordsRequest_FieldValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type SendRecordsRequest_FieldValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*SendRecordsRequest_FieldValue_StringValue) isSendRecordsRequest_FieldValue_Value() {}

func (*SendRecordsRequest_FieldValue_IntValue) isSendRecordsRequest_FieldValue_Value() {}

func (*SendRecordsRequest_FieldValue_LongValue) isSendRecordsRequest_FieldValue_Value() {}

func (*SendRecordsRequest_FieldValue_FloatValue) isSendRecordsRequest_FieldValue_Value() {}

func (*SendRecordsRequest_FieldValue_DoubleValue) isSendRecordsRequest_FieldValue_Value() {}

func (*SendRecordsRequest_FieldValue_BoolValue) isSendRecordsRequest_FieldValue_Value() {}

func (*SendRecordsRequest_FieldValue_BytesValue) isSendRecordsRequest_FieldValue_Value() {}

type SendRecordsRequest_IceRecord struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Fields        []*SendRecordsRequest_FieldValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	RecordType    string                           `protobuf:"bytes,2,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"` // "u", "c", "r"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRecordsRequest_IceRecord) Reset() {
	*x = SendRecordsRequest_IceRecord{}
	mi := &file_records_ingest_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRecordsRequest_IceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRecordsRequest_IceRecord) ProtoMessage() {}

func (x *SendRecordsRequest_IceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRecordsRequest_IceRecord.ProtoReflect.Descriptor instead.
func (*SendRecordsRequest_IceRecord) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{9, 1}
}

func (x *SendRecordsRequest_IceRecord) GetFields() []*SendRecordsRequest_FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SendRecordsRequest_IceRecord) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

// For arrow
type CommitRequest_PartitionValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*CommitRequest_PartitionValue_IntValue
	//	*CommitRequest_PartitionValue_LongValue
	//	*CommitRequest_PartitionValue_StringValue
	//	*CommitRequest_PartitionValue_FloatValue
	//	*CommitRequest_PartitionValue_DoubleValue
	//	*CommitRequest_PartitionValue_BoolValue
	Value         isCommitRequest_PartitionValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest_PartitionValue) Reset() {
	*x = CommitRequest_PartitionValue{}
	mi := &file_records_ingest_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest_PartitionValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest_PartitionValue) ProtoMessage() {}

func (x *CommitRequest_PartitionValue) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest_PartitionValue.ProtoReflect.Descriptor instead.
func (*CommitRequest_PartitionValue) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{19, 0}
}

func (x *CommitRequest_PartitionValue) GetValue() isCommitRequest_PartitionValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CommitRequest_PartitionValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*CommitRequest_PartitionValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *CommitRequest_PartitionValue) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*CommitRequest_PartitionValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *CommitRequest_PartitionValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*CommitRequest_PartitionValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *CommitRequest_PartitionValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*CommitRequest_PartitionValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *CommitRequest_PartitionValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*CommitRequest_PartitionValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *CommitRequest_PartitionValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*CommitRequest_PartitionValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isCommitRequest_PartitionValue_Value interface {
	isCommitRequest_PartitionValue_Value()
}

type CommitRequest_PartitionValue_IntValue struct {
	IntValue int32 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type CommitRequest_PartitionValue_LongValue struct {
	LongValue int64 `protobuf:"varint,2,opt,name=long_value,json=longValue,proto3,oneof"`
}

type CommitRequest_PartitionValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type CommitRequest_PartitionValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type CommitRequest_PartitionValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type CommitRequest_PartitionValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*CommitRequest_PartitionValue_IntValue) isCommitRequest_PartitionValue_Value() {}

func (*CommitRequest_PartitionValue_LongValue) isCommitRequest_PartitionValue_Value() {}

func (*CommitRequest_PartitionValue_StringValue) isCommitRequest_PartitionValue_Value() {}

func (*CommitRequest_PartitionValue_FloatValue) isCommitRequest_PartitionValue_Value() {}

func (*CommitRequest_PartitionValue_DoubleValue) isCommitRequest_PartitionValue_Value() {}

func (*CommitRequest_PartitionValue_BoolValue) isCommitRequest_PartitionValue_Value() {}

type CommitRequest_FileMetadata struct {
	state           protoimpl.MessageState          `protogen:"open.v1"`
	FileType        string                          `protobuf:"bytes,1,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FilePath        string                          `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	RecordCount     int64                           `protobuf:"varint,3,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	PartitionValues []*CommitRequest_PartitionValue `protobuf:"bytes,5,rep,name=partition_values,json=partitionValues,proto3" json:"partition_values,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitRequest_FileMetadata) Reset() {
	*x = CommitRequest_FileMetadata{}
	mi := &file_records_ingest_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest_FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest_FileMetadata) ProtoMessage() {}

func (x *CommitRequest_FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest_FileMetadata.ProtoReflect.Descriptor instead.
func (*CommitRequest_FileMetadata) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{19, 1}
}

func (x *CommitRequest_FileMetadata) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *CommitRequest_FileMetadata) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CommitRequest_FileMetadata) GetRecordCount() int64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *CommitRequest_FileMetadata) GetPartitionValues() []*CommitRequest_PartitionValue {
	if x != nil {
		return x.PartitionValues
	}
	return nil
}

var File_records_ingest_proto protoreflect.FileDescriptor

const file_records_ingest_proto_rawDesc = "" +
	"\n" +
	"\x14records_ingest.proto\x12\x1bio.olake.server.iceberg.rpc\":\n" +
	"\vSchemaField\x12\x19\n" +
	"\bice_type\x18\x01 \x01(\tR\aiceType\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"D\n" +
	"\x0ePartitionField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1c\n" +
	"\ttransform\x18\x02 \x01(\tR\ttransform\"k\n" +
	"\vTableConfig\x12&\n" +
	"\x0fdest_table_name\x18\x01 \x01(\tR\rdestTableName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06upsert\x18\x03 \x01(\bR\x06upsert\"U\n" +
	"\x16CheckConnectionRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\"1\n" +
	"\x17CheckConnectionResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"+\n" +
	"\x11DropTablesRequest\x12\x16\n" +
	"\x06tables\x18\x01 \x03(\tR\x06tables\",\n" +
	"\x12DropTablesResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\xd5\x02\n" +
	"\x12InitSessionRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12K\n" +
	"\ftable_config\x18\x02 \x01(\v2(.io.olake.server.iceberg.rpc.TableConfigR\vtableConfig\x12;\n" +
	"\x04mode\x18\x03 \x01(\x0e2'.io.olake.server.iceberg.rpc.WriterModeR\x04mode\x12@\n" +
	"\x06schema\x18\x04 \x03(\v2(.io.olake.server.iceberg.rpc.SchemaFieldR\x06schema\x12V\n" +
	"\x10partition_fields\x18\x05 \x03(\v2+.io.olake.server.iceberg.rpc.PartitionFieldR\x0fpartitionFields\"\xa7\x02\n" +
	"\x13InitSessionResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12&\n" +
	"\x0folake_2pc_state\x18\x02 \x01(\tR\rolake2pcState\x12\x1f\n" +
	"\vschema_json\x18\x03 \x01(\tR\n" +
	"schemaJson\x12l\n" +
	"\x0eicebergSchemas\x18\x04 \x03(\v2D.io.olake.server.iceberg.rpc.InitSessionResponse.IcebergSchemasEntryR\x0eicebergSchemas\x1aA\n" +
	"\x13IcebergSchemasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x04\n" +
	"\x12SendRecordsRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12@\n" +
	"\x06schema\x18\x02 \x03(\v2(.io.olake.server.iceberg.rpc.SchemaFieldR\x06schema\x12S\n" +
	"\arecords\x18\x03 \x03(\v29.io.olake.server.iceberg.rpc.SendRecordsRequest.IceRecordR\arecords\x1a\x86\x02\n" +
	"\n" +
	"FieldValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x05H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\x03 \x01(\x03H\x00R\tlongValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\a \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\x1a\x80\x01\n" +
	"\tIceRecord\x12R\n" +
	"\x06fields\x18\x01 \x03(\v2:.io.olake.server.iceberg.rpc.SendRecordsRequest.FieldValueR\x06fields\x12\x1f\n" +
	"\vrecord_type\x18\x02 \x01(\tR\n" +
	"recordType\"-\n" +
	"\x13SendRecordsResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"t\n" +
	"\x13EvolveSchemaRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12@\n" +
	"\x06schema\x18\x02 \x03(\v2(.io.olake.server.iceberg.rpc.SchemaFieldR\x06schema\"O\n" +
	"\x14EvolveSchemaResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x1f\n" +
	"\vschema_json\x18\x02 \x01(\tR\n" +
	"schemaJson\"8\n" +
	"\x19RefreshTableSchemaRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"U\n" +
	"\x1aRefreshTableSchemaResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x1f\n" +
	"\vschema_json\x18\x02 \x01(\tR\n" +
	"schemaJson\"1\n" +
	"\x12GetFilePathRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"-\n" +
	"\x13GetFilePathResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"j\n" +
	"\x11UploadFileRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_data\x18\x03 \x01(\fR\bfileData\",\n" +
	"\x12UploadFileResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\xe2\x04\n" +
	"\rCommitRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\\\n" +
	"\rfile_metadata\x18\x03 \x03(\v27.io.olake.server.iceberg.rpc.CommitRequest.FileMetadataR\ffileMetadata\x1a\xe7\x01\n" +
	"\x0ePartitionValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x05H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\x02 \x01(\x03H\x00R\tlongValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\x1a\xd1\x01\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\tfile_type\x18\x01 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12!\n" +
	"\frecord_count\x18\x03 \x01(\x03R\vrecordCount\x12d\n" +
	"\x10partition_values\x18\x05 \x03(\v29.io.olake.server.iceberg.rpc.CommitRequest.PartitionValueR\x0fpartitionValues\"(\n" +
	"\x0eCommitResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"2\n" +
	"\x13CloseSessionRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\".\n" +
	"\x14CloseSessionResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result*#\n" +
	"\n" +
	"WriterMode\x12\n" +
	"\n" +
	"\x06LEGACY\x10\x00\x12\t\n" +
	"\x05ARROW\x10\x012\xfd\x01\n" +
	"\x0eCatalogService\x12|\n" +
	"\x0fCheckConnection\x123.io.olake.server.iceberg.rpc.CheckConnectionRequest\x1a4.io.olake.server.iceberg.rpc.CheckConnectionResponse\x12m\n" +
	"\n" +
	"DropTables\x12..io.olake.server.iceberg.rpc.DropTablesRequest\x1a/.io.olake.server.iceberg.rpc.DropTablesResponse2\xa9\a\n" +
	"\rWriterService\x12p\n" +
	"\vInitSession\x12/.io.olake.server.iceberg.rpc.InitSessionRequest\x1a0.io.olake.server.iceberg.rpc.InitSessionResponse\x12p\n" +
	"\vSendRecords\x12/.io.olake.server.iceberg.rpc.SendRecordsRequest\x1a0.io.olake.server.iceberg.rpc.SendRecordsResponse\x12s\n" +
	"\fEvolveSchema\x120.io.olake.server.iceberg.rpc.EvolveSchemaRequest\x1a1.io.olake.server.iceberg.rpc.EvolveSchemaResponse\x12\x85\x01\n" +
	"\x12RefreshTableSchema\x126.io.olake.server.iceberg.rpc.RefreshTableSchemaRequest\x1a7.io.olake.server.iceberg.rpc.RefreshTableSchemaResponse\x12p\n" +
	"\vGetFilePath\x12/.io.olake.server.iceberg.rpc.GetFilePathRequest\x1a0.io.olake.server.iceberg.rpc.GetFilePathResponse\x12m\n" +
	"\n" +
	"UploadFile\x12..io.olake.server.iceberg.rpc.UploadFileRequest\x1a/.io.olake.server.iceberg.rpc.UploadFileResponse\x12a\n" +
	"\x06Commit\x12*.io.olake.server.iceberg.rpc.CommitRequest\x1a+.io.olake.server.iceberg.rpc.CommitResponse\x12s\n" +
	"\fCloseSession\x120.io.olake.server.iceberg.rpc.CloseSessionRequest\x1a1.io.olake.server.iceberg.rpc.CloseSessionResponseB\x1dB\fRecordIngestZ\riceberg/protob\x06proto3"

var (
	file_records_ingest_proto_rawDescOnce sync.Once
	file_records_ingest_proto_rawDescData []byte
)

func file_records_ingest_proto_rawDescGZIP() []byte {
	file_records_ingest_proto_rawDescOnce.Do(func() {
		file_records_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_records_ingest_proto_rawDesc), len(file_records_ingest_proto_rawDesc)))
	})
	return file_records_ingest_proto_rawDescData
}

var file_records_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_records_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_records_ingest_proto_goTypes = []any{
	(WriterMode)(0),                       // 0: io.olake.server.iceberg.rpc.WriterMode
	(*SchemaField)(nil),                   // 1: io.olake.server.iceberg.rpc.SchemaField
	(*PartitionField)(nil),                // 2: io.olake.server.iceberg.rpc.PartitionField
	(*TableConfig)(nil),                   // 3: io.olake.server.iceberg.rpc.TableConfig
	(*CheckConnectionRequest)(nil),        // 4: io.olake.server.iceberg.rpc.CheckConnectionRequest
	(*CheckConnectionResponse)(nil),       // 5: io.olake.server.iceberg.rpc.CheckConnectionResponse
	(*DropTablesRequest)(nil),             // 6: io.olake.server.iceberg.rpc.DropTablesRequest
	(*DropTablesResponse)(nil),            // 7: io.olake.server.iceberg.rpc.DropTablesResponse
	(*InitSessionRequest)(nil),            // 8: io.olake.server.iceberg.rpc.InitSessionRequest
	(*InitSessionResponse)(nil),           // 9: io.olake.server.iceberg.rpc.InitSessionResponse
	(*SendRecordsRequest)(nil),            // 10: io.olake.server.iceberg.rpc.SendRecordsRequest
	(*SendRecordsResponse)(nil),           // 11: io.olake.server.iceberg.rpc.SendRecordsResponse
	(*EvolveSchemaRequest)(nil),           // 12: io.olake.server.iceberg.rpc.EvolveSchemaRequest
	(*EvolveSchemaResponse)(nil),          // 13: io.olake.server.iceberg.rpc.EvolveSchemaResponse
	(*RefreshTableSchemaRequest)(nil),     // 14: io.olake.server.iceberg.rpc.RefreshTableSchemaRequest
	(*RefreshTableSchemaResponse)(nil),    // 15: io.olake.server.iceberg.rpc.RefreshTableSchemaResponse
	(*GetFilePathRequest)(nil),            // 16: io.olake.server.iceberg.rpc.GetFilePathRequest
	(*GetFilePathResponse)(nil),           // 17: io.olake.server.iceberg.rpc.GetFilePathResponse
	(*UploadFileRequest)(nil),             // 18: io.olake.server.iceberg.rpc.UploadFileRequest
	(*UploadFileResponse)(nil),            // 19: io.olake.server.iceberg.rpc.UploadFileResponse
	(*CommitRequest)(nil),                 // 20: io.olake.server.iceberg.rpc.CommitRequest
	(*CommitResponse)(nil),                // 21: io.olake.server.iceberg.rpc.CommitResponse
	(*CloseSessionRequest)(nil),           // 22: io.olake.server.iceberg.rpc.CloseSessionRequest
	(*CloseSessionResponse)(nil),          // 23: io.olake.server.iceberg.rpc.CloseSessionResponse
	nil,                                   // 24: io.olake.server.iceberg.rpc.InitSessionResponse.IcebergSchemasEntry
	(*SendRecordsRequest_FieldValue)(nil), // 25: io.olake.server.iceberg.rpc.SendRecordsRequest.FieldValue
	(*SendRecordsRequest_IceRecord)(nil),  // 26: io.olake.server.iceberg.rpc.SendRecordsRequest.IceRecord
	(*CommitRequest_PartitionValue)(nil),  // 27: io.olake.server.iceberg.rpc.CommitRequest.PartitionValue
	(*CommitRequest_FileMetadata)(nil),    // 28: io.olake.server.iceberg.rpc.CommitRequest.FileMetadata
}
var file_records_ingest_proto_depIdxs = []int32{
	3,  // 0: io.olake.server.iceberg.rpc.InitSessionRequest.table_config:type_name -> io.olake.server.iceberg.rpc.TableConfig
	0,  // 1: io.olake.server.iceberg.rpc.InitSessionRequest.mode:type_name -> io.olake.server.iceberg.rpc.WriterMode
	1,  // 2: io.olake.server.iceberg.rpc.InitSessionRequest.schema:type_name -> io.olake.server.iceberg.rpc.SchemaField
	2,  // 3: io.olake.server.iceberg.rpc.InitSessionRequest.partition_fields:type_name -> io.olake.server.iceberg.rpc.PartitionField
	24, // 4: io.olake.server.iceberg.rpc.InitSessionResponse.icebergSchemas:type_name -> io.olake.server.iceberg.rpc.InitSessionResponse.IcebergSchemasEntry
	1,  // 5: io.olake.server.iceberg.rpc.SendRecordsRequest.schema:type_name -> io.olake.server.iceberg.rpc.SchemaField
	26, // 6: io.olake.server.iceberg.rpc.SendRecordsRequest.records:type_name -> io.olake.server.iceberg.rpc.SendRecordsRequest.IceRecord
	1,  // 7: io.olake.server.iceberg.rpc.EvolveSchemaRequest.schema:type_name -> io.olake.server.iceberg.rpc.SchemaField
	28, // 8: io.olake.server.iceberg.rpc.CommitRequest.file_metadata:type_name -> io.olake.server.iceberg.rpc.CommitRequest.FileMetadata
	25, // 9: io.olake.server.iceberg.rpc.SendRecordsRequest.IceRecord.fields:type_name -> io.olake.server.iceberg.rpc.SendRecordsRequest.FieldValue
	27, // 10: io.olake.server.iceberg.rpc.CommitRequest.FileMetadata.partition_values:type_name -> io.olake.server.iceberg.rpc.CommitRequest.PartitionValue
	4,  // 11: io.olake.server.iceberg.rpc.CatalogService.CheckConnection:input_type -> io.olake.server.iceberg.rpc.CheckConnectionRequest
	6,  // 12: io.olake.server.iceberg.rpc.CatalogService.DropTables:input_type -> io.olake.server.iceberg.rpc.DropTablesRequest
	8,  // 13: io.olake.server.iceberg.rpc.WriterService.InitSession:input_type -> io.olake.server.iceberg.rpc.InitSessionRequest
	10, // 14: io.olake.server.iceberg.rpc.WriterService.SendRecords:input_type -> io.olake.server.iceberg.rpc.SendRecordsRequest
	12, // 15: io.olake.server.iceberg.rpc.WriterService.EvolveSchema:input_type -> io.olake.server.iceberg.rpc.EvolveSchemaRequest
	14, // 16: io.olake.server.iceberg.rpc.WriterService.RefreshTableSchema:input_type -> io.olake.server.iceberg.rpc.RefreshTableSchemaRequest
	16, // 17: io.olake.server.iceberg.rpc.WriterService.GetFilePath:input_type -> io.olake.server.iceberg.rpc.GetFilePathRequest
	18, // 18: io.olake.server.iceberg.rpc.WriterService.UploadFile:input_type -> io.olake.server.iceberg.rpc.UploadFileRequest
	20, // 19: io.olake.server.iceberg.rpc.WriterService.Commit:input_type -> io.olake.server.iceberg.rpc.CommitRequest
	22, // 20: io.olake.server.iceberg.rpc.WriterService.CloseSession:input_type -> io.olake.server.iceberg.rpc.CloseSessionRequest
	5,  // 21: io.olake.server.iceberg.rpc.CatalogService.CheckConnection:output_type -> io.olake.server.iceberg.rpc.CheckConnectionResponse
	7,  // 22: io.olake.server.iceberg.rpc.CatalogService.DropTables:output_type -> io.olake.server.iceberg.rpc.DropTablesResponse
	9,  // 23: io.olake.server.iceberg.rpc.WriterService.InitSession:output_type -> io.olake.server.iceberg.rpc.InitSessionResponse
	11, // 24: io.olake.server.iceberg.rpc.WriterService.SendRecords:output_type -> io.olake.server.iceberg.rpc.SendRecordsResponse
	13, // 25: io.olake.server.iceberg.rpc.WriterService.EvolveSchema:output_type -> io.olake.server.iceberg.rpc.EvolveSchemaResponse
	15, // 26: io.olake.server.iceberg.rpc.WriterService.RefreshTableSchema:output_type -> io.olake.server.iceberg.rpc.RefreshTableSchemaResponse
	17, // 27: io.olake.server.iceberg.rpc.WriterService.GetFilePath:output_type -> io.olake.server.iceberg.rpc.GetFilePathResponse
	19, // 28: io.olake.server.iceberg.rpc.WriterService.UploadFile:output_type -> io.olake.server.iceberg.rpc.UploadFileResponse
	21, // 29: io.olake.server.iceberg.rpc.WriterService.Commit:output_type -> io.olake.server.iceberg.rpc.CommitResponse
	23, // 30: io.olake.server.iceberg.rpc.WriterService.CloseSession:output_type -> io.olake.server.iceberg.rpc.CloseSessionResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_records_ingest_proto_init() }
func file_records_ingest_proto_init() {
	if File_records_ingest_proto != nil {
		return
	}
	file_records_ingest_proto_msgTypes[24].OneofWrappers = []any{
		(*SendRecordsRequest_FieldValue_StringValue)(nil),
		(*SendRecordsRequest_FieldValue_IntValue)(nil),
		(*SendRecordsRequest_FieldValue_LongValue)(nil),
		(*SendRecordsRequest_FieldValue_FloatValue)(nil),
		(*SendRecordsRequest_FieldValue_DoubleValue)(nil),
		(*SendRecordsRequest_FieldValue_BoolValue)(nil),
		(*SendRecordsRequest_FieldValue_BytesValue)(nil),
	}
	file_records_ingest_proto_msgTypes[26].OneofWrappers = []any{
		(*CommitRequest_PartitionValue_IntValue)(nil),
		(*CommitRequest_PartitionValue_LongValue)(nil),
		(*CommitRequest_PartitionValue_StringValue)(nil),
		(*CommitRequest_PartitionValue_FloatValue)(nil),
		(*CommitRequest_PartitionValue_DoubleValue)(nil),
		(*CommitRequest_PartitionValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_records_ingest_proto_rawDesc), len(file_records_ingest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_records_ingest_proto_goTypes,
		DependencyIndexes: file_records_ingest_proto_depIdxs,
		EnumInfos:         file_records_ingest_proto_enumTypes,
		MessageInfos:      file_records_ingest_proto_msgTypes,
	}.Build()
	File_records_ingest_proto = out.File
	file_records_ingest_proto_goTypes = nil
	file_records_ingest_proto_depIdxs = nil
}
