// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: records_ingest.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_CheckConnection_FullMethodName = "/io.olake.server.iceberg.rpc.CatalogService/CheckConnection"
	CatalogService_DropTables_FullMethodName      = "/io.olake.server.iceberg.rpc.CatalogService/DropTables"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================
// Catalog Service (Stateless)
// ============================================
type CatalogServiceClient interface {
	CheckConnection(ctx context.Context, in *CheckConnectionRequest, opts ...grpc.CallOption) (*CheckConnectionResponse, error)
	DropTables(ctx context.Context, in *DropTablesRequest, opts ...grpc.CallOption) (*DropTablesResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) CheckConnection(ctx context.Context, in *CheckConnectionRequest, opts ...grpc.CallOption) (*CheckConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckConnectionResponse)
	err := c.cc.Invoke(ctx, CatalogService_CheckConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DropTables(ctx context.Context, in *DropTablesRequest, opts ...grpc.CallOption) (*DropTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropTablesResponse)
	err := c.cc.Invoke(ctx, CatalogService_DropTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
//
// ============================================
// Catalog Service (Stateless)
// ============================================
type CatalogServiceServer interface {
	CheckConnection(context.Context, *CheckConnectionRequest) (*CheckConnectionResponse, error)
	DropTables(context.Context, *DropTablesRequest) (*DropTablesResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) CheckConnection(context.Context, *CheckConnectionRequest) (*CheckConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckConnection not implemented")
}
func (UnimplementedCatalogServiceServer) DropTables(context.Context, *DropTablesRequest) (*DropTablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropTables not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_CheckConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CheckConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CheckConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CheckConnection(ctx, req.(*CheckConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DropTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DropTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DropTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DropTables(ctx, req.(*DropTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.olake.server.iceberg.rpc.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckConnection",
			Handler:    _CatalogService_CheckConnection_Handler,
		},
		{
			MethodName: "DropTables",
			Handler:    _CatalogService_DropTables_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "records_ingest.proto",
}

const (
	WriterService_InitSession_FullMethodName        = "/io.olake.server.iceberg.rpc.WriterService/InitSession"
	WriterService_SendRecords_FullMethodName        = "/io.olake.server.iceberg.rpc.WriterService/SendRecords"
	WriterService_EvolveSchema_FullMethodName       = "/io.olake.server.iceberg.rpc.WriterService/EvolveSchema"
	WriterService_RefreshTableSchema_FullMethodName = "/io.olake.server.iceberg.rpc.WriterService/RefreshTableSchema"
	WriterService_GetFilePath_FullMethodName        = "/io.olake.server.iceberg.rpc.WriterService/GetFilePath"
	WriterService_UploadFile_FullMethodName         = "/io.olake.server.iceberg.rpc.WriterService/UploadFile"
	WriterService_Commit_FullMethodName             = "/io.olake.server.iceberg.rpc.WriterService/Commit"
	WriterService_CloseSession_FullMethodName       = "/io.olake.server.iceberg.rpc.WriterService/CloseSession"
)

// WriterServiceClient is the client API for WriterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================
// Unified Writer Service
// ============================================
type WriterServiceClient interface {
	InitSession(ctx context.Context, in *InitSessionRequest, opts ...grpc.CallOption) (*InitSessionResponse, error)
	// Row methods
	SendRecords(ctx context.Context, in *SendRecordsRequest, opts ...grpc.CallOption) (*SendRecordsResponse, error)
	EvolveSchema(ctx context.Context, in *EvolveSchemaRequest, opts ...grpc.CallOption) (*EvolveSchemaResponse, error)
	RefreshTableSchema(ctx context.Context, in *RefreshTableSchemaRequest, opts ...grpc.CallOption) (*RefreshTableSchemaResponse, error)
	// Arrow methods
	GetFilePath(ctx context.Context, in *GetFilePathRequest, opts ...grpc.CallOption) (*GetFilePathResponse, error)
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	// Common methods
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
}

type writerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWriterServiceClient(cc grpc.ClientConnInterface) WriterServiceClient {
	return &writerServiceClient{cc}
}

func (c *writerServiceClient) InitSession(ctx context.Context, in *InitSessionRequest, opts ...grpc.CallOption) (*InitSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitSessionResponse)
	err := c.cc.Invoke(ctx, WriterService_InitSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writerServiceClient) SendRecords(ctx context.Context, in *SendRecordsRequest, opts ...grpc.CallOption) (*SendRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendRecordsResponse)
	err := c.cc.Invoke(ctx, WriterService_SendRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writerServiceClient) EvolveSchema(ctx context.Context, in *EvolveSchemaRequest, opts ...grpc.CallOption) (*EvolveSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvolveSchemaResponse)
	err := c.cc.Invoke(ctx, WriterService_EvolveSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writerServiceClient) RefreshTableSchema(ctx context.Context, in *RefreshTableSchemaRequest, opts ...grpc.CallOption) (*RefreshTableSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTableSchemaResponse)
	err := c.cc.Invoke(ctx, WriterService_RefreshTableSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writerServiceClient) GetFilePath(ctx context.Context, in *GetFilePathRequest, opts ...grpc.CallOption) (*GetFilePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFilePathResponse)
	err := c.cc.Invoke(ctx, WriterService_GetFilePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writerServiceClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, WriterService_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writerServiceClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, WriterService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writerServiceClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, WriterService_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriterServiceServer is the server API for WriterService service.
// All implementations must embed UnimplementedWriterServiceServer
// for forward compatibility.
//
// ============================================
// Unified Writer Service
// ============================================
type WriterServiceServer interface {
	InitSession(context.Context, *InitSessionRequest) (*InitSessionResponse, error)
	// Row methods
	SendRecords(context.Context, *SendRecordsRequest) (*SendRecordsResponse, error)
	EvolveSchema(context.Context, *EvolveSchemaRequest) (*EvolveSchemaResponse, error)
	RefreshTableSchema(context.Context, *RefreshTableSchemaRequest) (*RefreshTableSchemaResponse, error)
	// Arrow methods
	GetFilePath(context.Context, *GetFilePathRequest) (*GetFilePathResponse, error)
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	// Common methods
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	mustEmbedUnimplementedWriterServiceServer()
}

// UnimplementedWriterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWriterServiceServer struct{}

func (UnimplementedWriterServiceServer) InitSession(context.Context, *InitSessionRequest) (*InitSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitSession not implemented")
}
func (UnimplementedWriterServiceServer) SendRecords(context.Context, *SendRecordsRequest) (*SendRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRecords not implemented")
}
func (UnimplementedWriterServiceServer) EvolveSchema(context.Context, *EvolveSchemaRequest) (*EvolveSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvolveSchema not implemented")
}
func (UnimplementedWriterServiceServer) RefreshTableSchema(context.Context, *RefreshTableSchemaRequest) (*RefreshTableSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshTableSchema not implemented")
}
func (UnimplementedWriterServiceServer) GetFilePath(context.Context, *GetFilePathRequest) (*GetFilePathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFilePath not implemented")
}
func (UnimplementedWriterServiceServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedWriterServiceServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedWriterServiceServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedWriterServiceServer) mustEmbedUnimplementedWriterServiceServer() {}
func (UnimplementedWriterServiceServer) testEmbeddedByValue()                       {}

// UnsafeWriterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WriterServiceServer will
// result in compilation errors.
type UnsafeWriterServiceServer interface {
	mustEmbedUnimplementedWriterServiceServer()
}

func RegisterWriterServiceServer(s grpc.ServiceRegistrar, srv WriterServiceServer) {
	// If the following call panics, it indicates UnimplementedWriterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WriterService_ServiceDesc, srv)
}

func _WriterService_InitSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).InitSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_InitSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).InitSession(ctx, req.(*InitSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriterService_SendRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).SendRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_SendRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).SendRecords(ctx, req.(*SendRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriterService_EvolveSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvolveSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).EvolveSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_EvolveSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).EvolveSchema(ctx, req.(*EvolveSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriterService_RefreshTableSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTableSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).RefreshTableSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_RefreshTableSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).RefreshTableSchema(ctx, req.(*RefreshTableSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriterService_GetFilePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).GetFilePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_GetFilePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).GetFilePath(ctx, req.(*GetFilePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriterService_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriterService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriterService_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WriterService_ServiceDesc is the grpc.ServiceDesc for WriterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WriterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.olake.server.iceberg.rpc.WriterService",
	HandlerType: (*WriterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitSession",
			Handler:    _WriterService_InitSession_Handler,
		},
		{
			MethodName: "SendRecords",
			Handler:    _WriterService_SendRecords_Handler,
		},
		{
			MethodName: "EvolveSchema",
			Handler:    _WriterService_EvolveSchema_Handler,
		},
		{
			MethodName: "RefreshTableSchema",
			Handler:    _WriterService_RefreshTableSchema_Handler,
		},
		{
			MethodName: "GetFilePath",
			Handler:    _WriterService_GetFilePath_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _WriterService_UploadFile_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _WriterService_Commit_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _WriterService_CloseSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "records_ingest.proto",
}
