// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: records_ingest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IcebergPayload_PayloadType int32

const (
	IcebergPayload_RECORDS              IcebergPayload_PayloadType = 0
	IcebergPayload_COMMIT               IcebergPayload_PayloadType = 1
	IcebergPayload_EVOLVE_SCHEMA        IcebergPayload_PayloadType = 2
	IcebergPayload_DROP_TABLE           IcebergPayload_PayloadType = 3
	IcebergPayload_GET_OR_CREATE_TABLE  IcebergPayload_PayloadType = 4
	IcebergPayload_REFRESH_TABLE_SCHEMA IcebergPayload_PayloadType = 5
	IcebergPayload_REGISTER             IcebergPayload_PayloadType = 6
	IcebergPayload_GET_FIELD_ID         IcebergPayload_PayloadType = 7
)

// Enum value maps for IcebergPayload_PayloadType.
var (
	IcebergPayload_PayloadType_name = map[int32]string{
		0: "RECORDS",
		1: "COMMIT",
		2: "EVOLVE_SCHEMA",
		3: "DROP_TABLE",
		4: "GET_OR_CREATE_TABLE",
		5: "REFRESH_TABLE_SCHEMA",
		6: "REGISTER",
		7: "GET_FIELD_ID",
	}
	IcebergPayload_PayloadType_value = map[string]int32{
		"RECORDS":              0,
		"COMMIT":               1,
		"EVOLVE_SCHEMA":        2,
		"DROP_TABLE":           3,
		"GET_OR_CREATE_TABLE":  4,
		"REFRESH_TABLE_SCHEMA": 5,
		"REGISTER":             6,
		"GET_FIELD_ID":         7,
	}
)

func (x IcebergPayload_PayloadType) Enum() *IcebergPayload_PayloadType {
	p := new(IcebergPayload_PayloadType)
	*p = x
	return p
}

func (x IcebergPayload_PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IcebergPayload_PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_records_ingest_proto_enumTypes[0].Descriptor()
}

func (IcebergPayload_PayloadType) Type() protoreflect.EnumType {
	return &file_records_ingest_proto_enumTypes[0]
}

func (x IcebergPayload_PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IcebergPayload_PayloadType.Descriptor instead.
func (IcebergPayload_PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 0}
}

type IcebergPayload struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          IcebergPayload_PayloadType  `protobuf:"varint,1,opt,name=type,proto3,enum=io.debezium.server.iceberg.rpc.IcebergPayload_PayloadType" json:"type,omitempty"`
	Metadata      *IcebergPayload_Metadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Records       []*IcebergPayload_IceRecord `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload) Reset() {
	*x = IcebergPayload{}
	mi := &file_records_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload) ProtoMessage() {}

func (x *IcebergPayload) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload.ProtoReflect.Descriptor instead.
func (*IcebergPayload) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IcebergPayload) GetType() IcebergPayload_PayloadType {
	if x != nil {
		return x.Type
	}
	return IcebergPayload_RECORDS
}

func (x *IcebergPayload) GetMetadata() *IcebergPayload_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IcebergPayload) GetRecords() []*IcebergPayload_IceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type RecordIngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordIngestResponse) Reset() {
	*x = RecordIngestResponse{}
	mi := &file_records_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordIngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordIngestResponse) ProtoMessage() {}

func (x *RecordIngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordIngestResponse.ProtoReflect.Descriptor instead.
func (*RecordIngestResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *RecordIngestResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RecordIngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ArrowFileUploadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DestTableName   string                 `protobuf:"bytes,1,opt,name=dest_table_name,json=destTableName,proto3" json:"dest_table_name,omitempty"`
	ThreadId        string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	FileData        []byte                 `protobuf:"bytes,3,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	FileType        string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"` // "data" or "delete"
	PartitionKey    string                 `protobuf:"bytes,5,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	Filename        string                 `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"`
	EqualityFieldId int32                  `protobuf:"varint,7,opt,name=equality_field_id,json=equalityFieldId,proto3" json:"equality_field_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArrowFileUploadRequest) Reset() {
	*x = ArrowFileUploadRequest{}
	mi := &file_records_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowFileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowFileUploadRequest) ProtoMessage() {}

func (x *ArrowFileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowFileUploadRequest.ProtoReflect.Descriptor instead.
func (*ArrowFileUploadRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *ArrowFileUploadRequest) GetDestTableName() string {
	if x != nil {
		return x.DestTableName
	}
	return ""
}

func (x *ArrowFileUploadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ArrowFileUploadRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *ArrowFileUploadRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *ArrowFileUploadRequest) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *ArrowFileUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ArrowFileUploadRequest) GetEqualityFieldId() int32 {
	if x != nil {
		return x.EqualityFieldId
	}
	return 0
}

type ArrowFileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoragePath   string                 `protobuf:"bytes,1,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowFileUploadResponse) Reset() {
	*x = ArrowFileUploadResponse{}
	mi := &file_records_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowFileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowFileUploadResponse) ProtoMessage() {}

func (x *ArrowFileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowFileUploadResponse.ProtoReflect.Descriptor instead.
func (*ArrowFileUploadResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *ArrowFileUploadResponse) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *ArrowFileUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ArrowFileUploadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ArrowFilenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DestTableName string                 `protobuf:"bytes,1,opt,name=dest_table_name,json=destTableName,proto3" json:"dest_table_name,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowFilenameRequest) Reset() {
	*x = ArrowFilenameRequest{}
	mi := &file_records_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowFilenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowFilenameRequest) ProtoMessage() {}

func (x *ArrowFilenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowFilenameRequest.ProtoReflect.Descriptor instead.
func (*ArrowFilenameRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *ArrowFilenameRequest) GetDestTableName() string {
	if x != nil {
		return x.DestTableName
	}
	return ""
}

func (x *ArrowFilenameRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type ArrowFilenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowFilenameResponse) Reset() {
	*x = ArrowFilenameResponse{}
	mi := &file_records_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowFilenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowFilenameResponse) ProtoMessage() {}

func (x *ArrowFilenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowFilenameResponse.ProtoReflect.Descriptor instead.
func (*ArrowFilenameResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *ArrowFilenameResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ArrowFilenameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ArrowFilenameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IcebergPayload_FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileType      string                 `protobuf:"bytes,1,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload_FileMetadata) Reset() {
	*x = IcebergPayload_FileMetadata{}
	mi := &file_records_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_FileMetadata) ProtoMessage() {}

func (x *IcebergPayload_FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_FileMetadata.ProtoReflect.Descriptor instead.
func (*IcebergPayload_FileMetadata) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IcebergPayload_FileMetadata) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *IcebergPayload_FileMetadata) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type IcebergPayload_Metadata struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	DestTableName   string                         `protobuf:"bytes,1,opt,name=dest_table_name,json=destTableName,proto3" json:"dest_table_name,omitempty"`
	ThreadId        string                         `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	IdentifierField *string                        `protobuf:"bytes,3,opt,name=identifier_field,json=identifierField,proto3,oneof" json:"identifier_field,omitempty"`
	Schema          []*IcebergPayload_SchemaField  `protobuf:"bytes,4,rep,name=schema,proto3" json:"schema,omitempty"`
	FileMetadata    []*IcebergPayload_FileMetadata `protobuf:"bytes,5,rep,name=file_metadata,json=fileMetadata,proto3" json:"file_metadata,omitempty"`
	FieldName       *string                        `protobuf:"bytes,6,opt,name=field_name,json=fieldName,proto3,oneof" json:"field_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IcebergPayload_Metadata) Reset() {
	*x = IcebergPayload_Metadata{}
	mi := &file_records_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_Metadata) ProtoMessage() {}

func (x *IcebergPayload_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_Metadata.ProtoReflect.Descriptor instead.
func (*IcebergPayload_Metadata) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 1}
}

func (x *IcebergPayload_Metadata) GetDestTableName() string {
	if x != nil {
		return x.DestTableName
	}
	return ""
}

func (x *IcebergPayload_Metadata) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *IcebergPayload_Metadata) GetIdentifierField() string {
	if x != nil && x.IdentifierField != nil {
		return *x.IdentifierField
	}
	return ""
}

func (x *IcebergPayload_Metadata) GetSchema() []*IcebergPayload_SchemaField {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *IcebergPayload_Metadata) GetFileMetadata() []*IcebergPayload_FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

func (x *IcebergPayload_Metadata) GetFieldName() string {
	if x != nil && x.FieldName != nil {
		return *x.FieldName
	}
	return ""
}

type IcebergPayload_SchemaField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IceType       string                 `protobuf:"bytes,1,opt,name=ice_type,json=iceType,proto3" json:"ice_type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload_SchemaField) Reset() {
	*x = IcebergPayload_SchemaField{}
	mi := &file_records_ingest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_SchemaField) ProtoMessage() {}

func (x *IcebergPayload_SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_SchemaField.ProtoReflect.Descriptor instead.
func (*IcebergPayload_SchemaField) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 2}
}

func (x *IcebergPayload_SchemaField) GetIceType() string {
	if x != nil {
		return x.IceType
	}
	return ""
}

func (x *IcebergPayload_SchemaField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// OPTIMIZED: Replace google.protobuf.Value with typed fields
type IcebergPayload_IceRecord struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Fields        []*IcebergPayload_IceRecord_FieldValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	RecordType    string                                 `protobuf:"bytes,2,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"` // "u", "c", "r"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload_IceRecord) Reset() {
	*x = IcebergPayload_IceRecord{}
	mi := &file_records_ingest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_IceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_IceRecord) ProtoMessage() {}

func (x *IcebergPayload_IceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_IceRecord.ProtoReflect.Descriptor instead.
func (*IcebergPayload_IceRecord) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 3}
}

func (x *IcebergPayload_IceRecord) GetFields() []*IcebergPayload_IceRecord_FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *IcebergPayload_IceRecord) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

// Use oneof for efficient memory usage - only one field type active per record field
type IcebergPayload_IceRecord_FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*IcebergPayload_IceRecord_FieldValue_StringValue
	//	*IcebergPayload_IceRecord_FieldValue_IntValue
	//	*IcebergPayload_IceRecord_FieldValue_LongValue
	//	*IcebergPayload_IceRecord_FieldValue_FloatValue
	//	*IcebergPayload_IceRecord_FieldValue_DoubleValue
	//	*IcebergPayload_IceRecord_FieldValue_BoolValue
	//	*IcebergPayload_IceRecord_FieldValue_BytesValue
	Value         isIcebergPayload_IceRecord_FieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload_IceRecord_FieldValue) Reset() {
	*x = IcebergPayload_IceRecord_FieldValue{}
	mi := &file_records_ingest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_IceRecord_FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_IceRecord_FieldValue) ProtoMessage() {}

func (x *IcebergPayload_IceRecord_FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_IceRecord_FieldValue.ProtoReflect.Descriptor instead.
func (*IcebergPayload_IceRecord_FieldValue) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *IcebergPayload_IceRecord_FieldValue) GetValue() isIcebergPayload_IceRecord_FieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *IcebergPayload_IceRecord_FieldValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *IcebergPayload_IceRecord_FieldValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *IcebergPayload_IceRecord_FieldValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isIcebergPayload_IceRecord_FieldValue_Value interface {
	isIcebergPayload_IceRecord_FieldValue_Value()
}

type IcebergPayload_IceRecord_FieldValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_IntValue struct {
	IntValue int32 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_LongValue struct {
	LongValue int64 `protobuf:"varint,3,opt,name=long_value,json=longValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*IcebergPayload_IceRecord_FieldValue_StringValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

func (*IcebergPayload_IceRecord_FieldValue_IntValue) isIcebergPayload_IceRecord_FieldValue_Value() {}

func (*IcebergPayload_IceRecord_FieldValue_LongValue) isIcebergPayload_IceRecord_FieldValue_Value() {}

func (*IcebergPayload_IceRecord_FieldValue_FloatValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

func (*IcebergPayload_IceRecord_FieldValue_DoubleValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

func (*IcebergPayload_IceRecord_FieldValue_BoolValue) isIcebergPayload_IceRecord_FieldValue_Value() {}

func (*IcebergPayload_IceRecord_FieldValue_BytesValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

var File_records_ingest_proto protoreflect.FileDescriptor

const file_records_ingest_proto_rawDesc = "" +
	"\n" +
	"\x14records_ingest.proto\x12\x1eio.debezium.server.iceberg.rpc\"\xc3\n" +
	"\n" +
	"\x0eIcebergPayload\x12N\n" +
	"\x04type\x18\x01 \x01(\x0e2:.io.debezium.server.iceberg.rpc.IcebergPayload.PayloadTypeR\x04type\x12S\n" +
	"\bmetadata\x18\x02 \x01(\v27.io.debezium.server.iceberg.rpc.IcebergPayload.MetadataR\bmetadata\x12R\n" +
	"\arecords\x18\x03 \x03(\v28.io.debezium.server.iceberg.rpc.IcebergPayload.IceRecordR\arecords\x1aH\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\tfile_type\x18\x01 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x1a\xfd\x02\n" +
	"\bMetadata\x12&\n" +
	"\x0fdest_table_name\x18\x01 \x01(\tR\rdestTableName\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12.\n" +
	"\x10identifier_field\x18\x03 \x01(\tH\x00R\x0fidentifierField\x88\x01\x01\x12R\n" +
	"\x06schema\x18\x04 \x03(\v2:.io.debezium.server.iceberg.rpc.IcebergPayload.SchemaFieldR\x06schema\x12`\n" +
	"\rfile_metadata\x18\x05 \x03(\v2;.io.debezium.server.iceberg.rpc.IcebergPayload.FileMetadataR\ffileMetadata\x12\"\n" +
	"\n" +
	"field_name\x18\x06 \x01(\tH\x01R\tfieldName\x88\x01\x01B\x13\n" +
	"\x11_identifier_fieldB\r\n" +
	"\v_field_name\x1a:\n" +
	"\vSchemaField\x12\x19\n" +
	"\bice_type\x18\x01 \x01(\tR\aiceType\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x1a\x92\x03\n" +
	"\tIceRecord\x12[\n" +
	"\x06fields\x18\x01 \x03(\v2C.io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord.FieldValueR\x06fields\x12\x1f\n" +
	"\vrecord_type\x18\x02 \x01(\tR\n" +
	"recordType\x1a\x86\x02\n" +
	"\n" +
	"FieldValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x05H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\x03 \x01(\x03H\x00R\tlongValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\a \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\x9c\x01\n" +
	"\vPayloadType\x12\v\n" +
	"\aRECORDS\x10\x00\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x01\x12\x11\n" +
	"\rEVOLVE_SCHEMA\x10\x02\x12\x0e\n" +
	"\n" +
	"DROP_TABLE\x10\x03\x12\x17\n" +
	"\x13GET_OR_CREATE_TABLE\x10\x04\x12\x18\n" +
	"\x14REFRESH_TABLE_SCHEMA\x10\x05\x12\f\n" +
	"\bREGISTER\x10\x06\x12\x10\n" +
	"\fGET_FIELD_ID\x10\a\"H\n" +
	"\x14RecordIngestResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x84\x02\n" +
	"\x16ArrowFileUploadRequest\x12&\n" +
	"\x0fdest_table_name\x18\x01 \x01(\tR\rdestTableName\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x1b\n" +
	"\tfile_data\x18\x03 \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\x12#\n" +
	"\rpartition_key\x18\x05 \x01(\tR\fpartitionKey\x12\x1a\n" +
	"\bfilename\x18\x06 \x01(\tR\bfilename\x12*\n" +
	"\x11equality_field_id\x18\a \x01(\x05R\x0fequalityFieldId\"l\n" +
	"\x17ArrowFileUploadResponse\x12!\n" +
	"\fstorage_path\x18\x01 \x01(\tR\vstoragePath\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"[\n" +
	"\x14ArrowFilenameRequest\x12&\n" +
	"\x0fdest_table_name\x18\x01 \x01(\tR\rdestTableName\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"c\n" +
	"\x15ArrowFilenameResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x8a\x01\n" +
	"\x13RecordIngestService\x12s\n" +
	"\vSendRecords\x12..io.debezium.server.iceberg.rpc.IcebergPayload\x1a4.io.debezium.server.iceberg.rpc.RecordIngestResponse2\x9a\x02\n" +
	"\x18ArrowRecordIngestService\x12}\n" +
	"\n" +
	"UploadFile\x126.io.debezium.server.iceberg.rpc.ArrowFileUploadRequest\x1a7.io.debezium.server.iceberg.rpc.ArrowFileUploadResponse\x12\x7f\n" +
	"\x10GenerateFilename\x124.io.debezium.server.iceberg.rpc.ArrowFilenameRequest\x1a5.io.debezium.server.iceberg.rpc.ArrowFilenameResponseB\x0fZ\riceberg/protob\x06proto3"

var (
	file_records_ingest_proto_rawDescOnce sync.Once
	file_records_ingest_proto_rawDescData []byte
)

func file_records_ingest_proto_rawDescGZIP() []byte {
	file_records_ingest_proto_rawDescOnce.Do(func() {
		file_records_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_records_ingest_proto_rawDesc), len(file_records_ingest_proto_rawDesc)))
	})
	return file_records_ingest_proto_rawDescData
}

var file_records_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_records_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_records_ingest_proto_goTypes = []any{
	(IcebergPayload_PayloadType)(0),             // 0: io.debezium.server.iceberg.rpc.IcebergPayload.PayloadType
	(*IcebergPayload)(nil),                      // 1: io.debezium.server.iceberg.rpc.IcebergPayload
	(*RecordIngestResponse)(nil),                // 2: io.debezium.server.iceberg.rpc.RecordIngestResponse
	(*ArrowFileUploadRequest)(nil),              // 3: io.debezium.server.iceberg.rpc.ArrowFileUploadRequest
	(*ArrowFileUploadResponse)(nil),             // 4: io.debezium.server.iceberg.rpc.ArrowFileUploadResponse
	(*ArrowFilenameRequest)(nil),                // 5: io.debezium.server.iceberg.rpc.ArrowFilenameRequest
	(*ArrowFilenameResponse)(nil),               // 6: io.debezium.server.iceberg.rpc.ArrowFilenameResponse
	(*IcebergPayload_FileMetadata)(nil),         // 7: io.debezium.server.iceberg.rpc.IcebergPayload.FileMetadata
	(*IcebergPayload_Metadata)(nil),             // 8: io.debezium.server.iceberg.rpc.IcebergPayload.Metadata
	(*IcebergPayload_SchemaField)(nil),          // 9: io.debezium.server.iceberg.rpc.IcebergPayload.SchemaField
	(*IcebergPayload_IceRecord)(nil),            // 10: io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord
	(*IcebergPayload_IceRecord_FieldValue)(nil), // 11: io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord.FieldValue
}
var file_records_ingest_proto_depIdxs = []int32{
	0,  // 0: io.debezium.server.iceberg.rpc.IcebergPayload.type:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.PayloadType
	8,  // 1: io.debezium.server.iceberg.rpc.IcebergPayload.metadata:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.Metadata
	10, // 2: io.debezium.server.iceberg.rpc.IcebergPayload.records:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord
	9,  // 3: io.debezium.server.iceberg.rpc.IcebergPayload.Metadata.schema:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.SchemaField
	7,  // 4: io.debezium.server.iceberg.rpc.IcebergPayload.Metadata.file_metadata:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.FileMetadata
	11, // 5: io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord.fields:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord.FieldValue
	1,  // 6: io.debezium.server.iceberg.rpc.RecordIngestService.SendRecords:input_type -> io.debezium.server.iceberg.rpc.IcebergPayload
	3,  // 7: io.debezium.server.iceberg.rpc.ArrowRecordIngestService.UploadFile:input_type -> io.debezium.server.iceberg.rpc.ArrowFileUploadRequest
	5,  // 8: io.debezium.server.iceberg.rpc.ArrowRecordIngestService.GenerateFilename:input_type -> io.debezium.server.iceberg.rpc.ArrowFilenameRequest
	2,  // 9: io.debezium.server.iceberg.rpc.RecordIngestService.SendRecords:output_type -> io.debezium.server.iceberg.rpc.RecordIngestResponse
	4,  // 10: io.debezium.server.iceberg.rpc.ArrowRecordIngestService.UploadFile:output_type -> io.debezium.server.iceberg.rpc.ArrowFileUploadResponse
	6,  // 11: io.debezium.server.iceberg.rpc.ArrowRecordIngestService.GenerateFilename:output_type -> io.debezium.server.iceberg.rpc.ArrowFilenameResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_records_ingest_proto_init() }
func file_records_ingest_proto_init() {
	if File_records_ingest_proto != nil {
		return
	}
	file_records_ingest_proto_msgTypes[7].OneofWrappers = []any{}
	file_records_ingest_proto_msgTypes[10].OneofWrappers = []any{
		(*IcebergPayload_IceRecord_FieldValue_StringValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_IntValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_LongValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_FloatValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_DoubleValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_BoolValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_records_ingest_proto_rawDesc), len(file_records_ingest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_records_ingest_proto_goTypes,
		DependencyIndexes: file_records_ingest_proto_depIdxs,
		EnumInfos:         file_records_ingest_proto_enumTypes,
		MessageInfos:      file_records_ingest_proto_msgTypes,
	}.Build()
	File_records_ingest_proto = out.File
	file_records_ingest_proto_goTypes = nil
	file_records_ingest_proto_depIdxs = nil
}
