// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: toast_read.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToastReadService_ReadRows_FullMethodName       = "/io.debezium.server.iceberg.rpc.ToastReadService/ReadRows"
	ToastReadService_FlushOpenFiles_FullMethodName = "/io.debezium.server.iceberg.rpc.ToastReadService/FlushOpenFiles"
)

// ToastReadServiceClient is the client API for ToastReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ToastReadService serves values a CDC change could not carry (Postgres omits unchanged
// out-of-line columns from an UPDATE) by reading them out of the rows the destination
// table already holds. Both calls reuse the session created by GET_OR_CREATE_TABLE.
type ToastReadServiceClient interface {
	// ReadRows streams the requested columns of the rows addressed by data file and position.
	ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadRowsBatch], error)
	// FlushOpenFiles closes the data files this thread's writer still holds open, without
	// committing them, so rows written earlier in the same sync become readable.
	FlushOpenFiles(ctx context.Context, in *FlushOpenFilesRequest, opts ...grpc.CallOption) (*FlushOpenFilesResponse, error)
}

type toastReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToastReadServiceClient(cc grpc.ClientConnInterface) ToastReadServiceClient {
	return &toastReadServiceClient{cc}
}

func (c *toastReadServiceClient) ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadRowsBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToastReadService_ServiceDesc.Streams[0], ToastReadService_ReadRows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadRowsRequest, ReadRowsBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToastReadService_ReadRowsClient = grpc.ServerStreamingClient[ReadRowsBatch]

func (c *toastReadServiceClient) FlushOpenFiles(ctx context.Context, in *FlushOpenFilesRequest, opts ...grpc.CallOption) (*FlushOpenFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushOpenFilesResponse)
	err := c.cc.Invoke(ctx, ToastReadService_FlushOpenFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToastReadServiceServer is the server API for ToastReadService service.
// All implementations must embed UnimplementedToastReadServiceServer
// for forward compatibility.
//
// ToastReadService serves values a CDC change could not carry (Postgres omits unchanged
// out-of-line columns from an UPDATE) by reading them out of the rows the destination
// table already holds. Both calls reuse the session created by GET_OR_CREATE_TABLE.
type ToastReadServiceServer interface {
	// ReadRows streams the requested columns of the rows addressed by data file and position.
	ReadRows(*ReadRowsRequest, grpc.ServerStreamingServer[ReadRowsBatch]) error
	// FlushOpenFiles closes the data files this thread's writer still holds open, without
	// committing them, so rows written earlier in the same sync become readable.
	FlushOpenFiles(context.Context, *FlushOpenFilesRequest) (*FlushOpenFilesResponse, error)
	mustEmbedUnimplementedToastReadServiceServer()
}

// UnimplementedToastReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToastReadServiceServer struct{}

func (UnimplementedToastReadServiceServer) ReadRows(*ReadRowsRequest, grpc.ServerStreamingServer[ReadRowsBatch]) error {
	return status.Error(codes.Unimplemented, "method ReadRows not implemented")
}
func (UnimplementedToastReadServiceServer) FlushOpenFiles(context.Context, *FlushOpenFilesRequest) (*FlushOpenFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushOpenFiles not implemented")
}
func (UnimplementedToastReadServiceServer) mustEmbedUnimplementedToastReadServiceServer() {}
func (UnimplementedToastReadServiceServer) testEmbeddedByValue()                          {}

// UnsafeToastReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToastReadServiceServer will
// result in compilation errors.
type UnsafeToastReadServiceServer interface {
	mustEmbedUnimplementedToastReadServiceServer()
}

func RegisterToastReadServiceServer(s grpc.ServiceRegistrar, srv ToastReadServiceServer) {
	// If the following call panics, it indicates UnimplementedToastReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToastReadService_ServiceDesc, srv)
}

func _ToastReadService_ReadRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToastReadServiceServer).ReadRows(m, &grpc.GenericServerStream[ReadRowsRequest, ReadRowsBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToastReadService_ReadRowsServer = grpc.ServerStreamingServer[ReadRowsBatch]

func _ToastReadService_FlushOpenFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushOpenFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToastReadServiceServer).FlushOpenFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToastReadService_FlushOpenFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToastReadServiceServer).FlushOpenFiles(ctx, req.(*FlushOpenFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToastReadService_ServiceDesc is the grpc.ServiceDesc for ToastReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToastReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.debezium.server.iceberg.rpc.ToastReadService",
	HandlerType: (*ToastReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FlushOpenFiles",
			Handler:    _ToastReadService_FlushOpenFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadRows",
			Handler:       _ToastReadService_ReadRows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "toast_read.proto",
}
