// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: toast_read.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadRowsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ThreadId string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	// Table columns to project, by name.
	Columns       []string                    `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Files         []*ReadRowsRequest_FileRows `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRowsRequest) Reset() {
	*x = ReadRowsRequest{}
	mi := &file_toast_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRowsRequest) ProtoMessage() {}

func (x *ReadRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_toast_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRowsRequest.ProtoReflect.Descriptor instead.
func (*ReadRowsRequest) Descriptor() ([]byte, []int) {
	return file_toast_read_proto_rawDescGZIP(), []int{0}
}

func (x *ReadRowsRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ReadRowsRequest) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ReadRowsRequest) GetFiles() []*ReadRowsRequest_FileRows {
	if x != nil {
		return x.Files
	}
	return nil
}

// ColumnValue carries one stored value; an unset oneof means the value is NULL.
type ColumnValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ColumnValue_StringValue
	//	*ColumnValue_LongValue
	//	*ColumnValue_DoubleValue
	//	*ColumnValue_BoolValue
	//	*ColumnValue_BytesValue
	Value         isColumnValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnValue) Reset() {
	*x = ColumnValue{}
	mi := &file_toast_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnValue) ProtoMessage() {}

func (x *ColumnValue) ProtoReflect() protoreflect.Message {
	mi := &file_toast_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnValue.ProtoReflect.Descriptor instead.
func (*ColumnValue) Descriptor() ([]byte, []int) {
	return file_toast_read_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnValue) GetValue() isColumnValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ColumnValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ColumnValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ColumnValue) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*ColumnValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *ColumnValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*ColumnValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *ColumnValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ColumnValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *ColumnValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*ColumnValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isColumnValue_Value interface {
	isColumnValue_Value()
}

type ColumnValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ColumnValue_LongValue struct {
	LongValue int64 `protobuf:"varint,2,opt,name=long_value,json=longValue,proto3,oneof"`
}

type ColumnValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type ColumnValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type ColumnValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*ColumnValue_StringValue) isColumnValue_Value() {}

func (*ColumnValue_LongValue) isColumnValue_Value() {}

func (*ColumnValue_DoubleValue) isColumnValue_Value() {}

func (*ColumnValue_BoolValue) isColumnValue_Value() {}

func (*ColumnValue_BytesValue) isColumnValue_Value() {}

type ReadRowsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*ReadRowsBatch_Row   `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRowsBatch) Reset() {
	*x = ReadRowsBatch{}
	mi := &file_toast_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRowsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRowsBatch) ProtoMessage() {}

func (x *ReadRowsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_toast_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRowsBatch.ProtoReflect.Descriptor instead.
func (*ReadRowsBatch) Descriptor() ([]byte, []int) {
	return file_toast_read_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRowsBatch) GetRows() []*ReadRowsBatch_Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type FlushOpenFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushOpenFilesRequest) Reset() {
	*x = FlushOpenFilesRequest{}
	mi := &file_toast_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushOpenFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushOpenFilesRequest) ProtoMessage() {}

func (x *FlushOpenFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_toast_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushOpenFilesRequest.ProtoReflect.Descriptor instead.
func (*FlushOpenFilesRequest) Descriptor() ([]byte, []int) {
	return file_toast_read_proto_rawDescGZIP(), []int{3}
}

func (x *FlushOpenFilesRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type FlushOpenFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlushedFiles  int64                  `protobuf:"varint,1,opt,name=flushed_files,json=flushedFiles,proto3" json:"flushed_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushOpenFilesResponse) Reset() {
	*x = FlushOpenFilesResponse{}
	mi := &file_toast_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushOpenFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushOpenFilesResponse) ProtoMessage() {}

func (x *FlushOpenFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_toast_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushOpenFilesResponse.ProtoReflect.Descriptor instead.
func (*FlushOpenFilesResponse) Descriptor() ([]byte, []int) {
	return file_toast_read_proto_rawDescGZIP(), []int{4}
}

func (x *FlushOpenFilesResponse) GetFlushedFiles() int64 {
	if x != nil {
		return x.FlushedFiles
	}
	return 0
}

type ReadRowsRequest_FileRows struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	FilePath string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	// Row positions to read, ascending.
	Positions     []int64 `protobuf:"varint,2,rep,packed,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRowsRequest_FileRows) Reset() {
	*x = ReadRowsRequest_FileRows{}
	mi := &file_toast_read_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRowsRequest_FileRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRowsRequest_FileRows) ProtoMessage() {}

func (x *ReadRowsRequest_FileRows) ProtoReflect() protoreflect.Message {
	mi := &file_toast_read_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRowsRequest_FileRows.ProtoReflect.Descriptor instead.
func (*ReadRowsRequest_FileRows) Descriptor() ([]byte, []int) {
	return file_toast_read_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReadRowsRequest_FileRows) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ReadRowsRequest_FileRows) GetPositions() []int64 {
	if x != nil {
		return x.Positions
	}
	return nil
}

type ReadRowsBatch_Row struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	FilePath string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Position int64                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	// One entry per requested column, in request order.
	Values        []*ColumnValue `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRowsBatch_Row) Reset() {
	*x = ReadRowsBatch_Row{}
	mi := &file_toast_read_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRowsBatch_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRowsBatch_Row) ProtoMessage() {}

func (x *ReadRowsBatch_Row) ProtoReflect() protoreflect.Message {
	mi := &file_toast_read_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRowsBatch_Row.ProtoReflect.Descriptor instead.
func (*ReadRowsBatch_Row) Descriptor() ([]byte, []int) {
	return file_toast_read_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ReadRowsBatch_Row) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ReadRowsBatch_Row) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ReadRowsBatch_Row) GetValues() []*ColumnValue {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_toast_read_proto protoreflect.FileDescriptor

const file_toast_read_proto_rawDesc = "" +
	"\n" +
	"\x10toast_read.proto\x12\x14io.olake.iceberg.rpc\"\xd5\x01\n" +
	"\x0fReadRowsRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12D\n" +
	"\x05files\x18\x03 \x03(\v2..io.olake.iceberg.rpc.ReadRowsRequest.FileRowsR\x05files\x1aE\n" +
	"\bFileRows\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1c\n" +
	"\tpositions\x18\x02 \x03(\x03R\tpositions\"\xc5\x01\n" +
	"\vColumnValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\x02 \x01(\x03H\x00R\tlongValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\xc7\x01\n" +
	"\rReadRowsBatch\x12;\n" +
	"\x04rows\x18\x01 \x03(\v2'.io.olake.iceberg.rpc.ReadRowsBatch.RowR\x04rows\x1ay\n" +
	"\x03Row\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x03R\bposition\x129\n" +
	"\x06values\x18\x03 \x03(\v2!.io.olake.iceberg.rpc.ColumnValueR\x06values\"4\n" +
	"\x15FlushOpenFilesRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"=\n" +
	"\x16FlushOpenFilesResponse\x12#\n" +
	"\rflushed_files\x18\x01 \x01(\x03R\fflushedFiles2\xd9\x01\n" +
	"\x10ToastReadService\x12X\n" +
	"\bReadRows\x12%.io.olake.iceberg.rpc.ReadRowsRequest\x1a#.io.olake.iceberg.rpc.ReadRowsBatch0\x01\x12k\n" +
	"\x0eFlushOpenFiles\x12+.io.olake.iceberg.rpc.FlushOpenFilesRequest\x1a,.io.olake.iceberg.rpc.FlushOpenFilesResponseB\x1aB\tToastReadZ\riceberg/protob\x06proto3"

var (
	file_toast_read_proto_rawDescOnce sync.Once
	file_toast_read_proto_rawDescData []byte
)

func file_toast_read_proto_rawDescGZIP() []byte {
	file_toast_read_proto_rawDescOnce.Do(func() {
		file_toast_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_toast_read_proto_rawDesc), len(file_toast_read_proto_rawDesc)))
	})
	return file_toast_read_proto_rawDescData
}

var file_toast_read_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_toast_read_proto_goTypes = []any{
	(*ReadRowsRequest)(nil),          // 0: io.olake.iceberg.rpc.ReadRowsRequest
	(*ColumnValue)(nil),              // 1: io.olake.iceberg.rpc.ColumnValue
	(*ReadRowsBatch)(nil),            // 2: io.olake.iceberg.rpc.ReadRowsBatch
	(*FlushOpenFilesRequest)(nil),    // 3: io.olake.iceberg.rpc.FlushOpenFilesRequest
	(*FlushOpenFilesResponse)(nil),   // 4: io.olake.iceberg.rpc.FlushOpenFilesResponse
	(*ReadRowsRequest_FileRows)(nil), // 5: io.olake.iceberg.rpc.ReadRowsRequest.FileRows
	(*ReadRowsBatch_Row)(nil),        // 6: io.olake.iceberg.rpc.ReadRowsBatch.Row
}
var file_toast_read_proto_depIdxs = []int32{
	5, // 0: io.olake.iceberg.rpc.ReadRowsRequest.files:type_name -> io.olake.iceberg.rpc.ReadRowsRequest.FileRows
	6, // 1: io.olake.iceberg.rpc.ReadRowsBatch.rows:type_name -> io.olake.iceberg.rpc.ReadRowsBatch.Row
	1, // 2: io.olake.iceberg.rpc.ReadRowsBatch.Row.values:type_name -> io.olake.iceberg.rpc.ColumnValue
	0, // 3: io.olake.iceberg.rpc.ToastReadService.ReadRows:input_type -> io.olake.iceberg.rpc.ReadRowsRequest
	3, // 4: io.olake.iceberg.rpc.ToastReadService.FlushOpenFiles:input_type -> io.olake.iceberg.rpc.FlushOpenFilesRequest
	2, // 5: io.olake.iceberg.rpc.ToastReadService.ReadRows:output_type -> io.olake.iceberg.rpc.ReadRowsBatch
	4, // 6: io.olake.iceberg.rpc.ToastReadService.FlushOpenFiles:output_type -> io.olake.iceberg.rpc.FlushOpenFilesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_toast_read_proto_init() }
func file_toast_read_proto_init() {
	if File_toast_read_proto != nil {
		return
	}
	file_toast_read_proto_msgTypes[1].OneofWrappers = []any{
		(*ColumnValue_StringValue)(nil),
		(*ColumnValue_LongValue)(nil),
		(*ColumnValue_DoubleValue)(nil),
		(*ColumnValue_BoolValue)(nil),
		(*ColumnValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_toast_read_proto_rawDesc), len(file_toast_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_toast_read_proto_goTypes,
		DependencyIndexes: file_toast_read_proto_depIdxs,
		MessageInfos:      file_toast_read_proto_msgTypes,
	}.Build()
	File_toast_read_proto = out.File
	file_toast_read_proto_goTypes = nil
	file_toast_read_proto_depIdxs = nil
}
