package driver

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/datazip-inc/olake/utils"
	_ "github.com/ibmdb/go_ibm_db"
	"github.com/jmoiron/sqlx"
	"github.com/stretchr/testify/require"
)

func ExecuteQuery(ctx context.Context, t *testing.T, streams []string, operation string, fileConfig bool) {
	t.Helper()

	var dsn string
	if fileConfig {
		var config Config
		utils.UnmarshalFile("./testdata/source.json", &config, false)
		dsn = config.BuildDSN()
	} else {
		dsn = "HOSTNAME=localhost;PORT=50000;DATABASE=testdb;UID=db2inst1;PWD=secret1234;"
	}

	db, err := sqlx.ConnectContext(ctx, "go_ibm_db", dsn)
	require.NoError(t, err, "failed to connect to db2")
	defer func() {
		require.NoError(t, db.Close())
	}()

	integrationTestTable := streams[0]
	var query string

	switch operation {
	case "create":
		query = fmt.Sprintf(`
			CREATE TABLE %s (
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				col_cursor INTEGER,
				col_bigint BIGINT,
				col_char CHAR(1),
				col_character CHAR(10),
				col_varchar VARCHAR(50),
				col_date DATE,
				col_decimal DECIMAL(10, 2),
				col_double DOUBLE,
				col_real REAL,
				col_int INTEGER,
				col_smallint SMALLINT,
				col_clob CLOB(1M),
				col_blob BLOB(1M),
				col_timestamp TIMESTAMP,
				col_time TIME,
				col_graphic GRAPHIC(11),
				col_vargraphic VARGRAPHIC(14)
			)`, integrationTestTable)

	case "drop":
		query = fmt.Sprintf(`DROP TABLE %s`, integrationTestTable)
		_, _ = db.ExecContext(ctx, query) // Ignore error if table doesn't exist
		return

	case "clean":
		query = fmt.Sprintf("DELETE FROM %s", integrationTestTable)

	case "add":
		insertTestData(t, ctx, db, integrationTestTable)
		return

	case "insert":
		query = fmt.Sprintf(`
			INSERT INTO %s (
				col_cursor, col_bigint, col_char, col_character,
				col_varchar, col_date, col_decimal,
				col_double, col_real, col_int, col_smallint,
				col_clob, col_blob, col_timestamp, col_time,
				col_graphic, col_vargraphic
			) VALUES (
				6, 12345678901234, 'c', 'char_val',
				'varchar_val', DATE('2023-01-01'), 123.45,
				123.456789, 123.5, 123, 123,
				CLOB('sample text'), BLOB(X'424C4F422044415441204F4E45'),
				TIMESTAMP('2023-01-01-12.00.00.000000'),
				TIME('12.00.00'),
				GRAPHIC('graphic_val'),
				VARGRAPHIC('vargraphic_val')
			)`, integrationTestTable)

	case "update":
		query = fmt.Sprintf(`
        UPDATE %s SET
            col_cursor = NULL,
            col_smallint = 321
        WHERE id = 1`, integrationTestTable)

	case "delete":
		query = fmt.Sprintf("DELETE FROM %s WHERE id = 1", integrationTestTable)

	case "evolve-schema":
		evolveQuery := fmt.Sprintf(`ALTER TABLE DB2INST1.%s ALTER COLUMN COL_INT SET DATA TYPE BIGINT`, integrationTestTable)
		_, err = db.ExecContext(ctx, evolveQuery)
		require.NoError(t, err, "Failed to execute %s operation", operation)

		// to clear REORG pending state of DB2 after schema evolution
		query = fmt.Sprintf(`CALL SYSPROC.ADMIN_CMD('REORG TABLE DB2INST1.%s')`, integrationTestTable)

	case "populate-stats":
		// if table exists, run stats for DB2 to populate stats
		query = fmt.Sprintf(`CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE DB2INST1.%s WITH DISTRIBUTION AND DETAILED INDEXES ALL')`, integrationTestTable)

	default:
		t.Fatalf("Unsupported operation: %s", operation)
	}

	_, err = db.ExecContext(ctx, query)
	require.NoError(t, err, "Failed to execute %s operation", operation)
}

func insertTestData(t *testing.T, ctx context.Context, db *sqlx.DB, tableName string) {
	t.Helper()

	for i := 1; i <= 5; i++ {
		query := fmt.Sprintf(`
		INSERT INTO %s (
			col_cursor, col_bigint, col_char, col_character,
			col_varchar, col_date, col_decimal,
			col_double, col_real, col_int, col_smallint,
			col_clob, col_blob, col_timestamp, col_time,
			col_graphic, col_vargraphic
		) VALUES (
			%d, 12345678901234, 'c', 'char_val',
			'varchar_val', DATE('2023-01-01'), 123.45,
			123.456789, 123.5, 123, 123,
			CLOB('sample text'), BLOB(X'424C4F422044415441204F4E45'),
			TIMESTAMP('2023-01-01-12.00.00.000000'),
			TIME('12.00.00'),
			GRAPHIC('graphic_val'),
			VARGRAPHIC('vargraphic_val')
		)`, tableName, i)

		_, err := db.ExecContext(ctx, query)
		require.NoError(t, err, "Failed to insert test data")
	}
}

var ExpectedDB2Data = map[string]interface{}{
	"col_bigint":     int64(12345678901234),
	"col_char":       "c",
	"col_character":  "char_val",
	"col_varchar":    "varchar_val",
	"col_date":       arrow.Timestamp(time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_decimal":    float64(123.45),
	"col_double":     123.456789,
	"col_real":       float32(123.5),
	"col_int":        int32(123),
	"col_smallint":   int32(123),
	"col_clob":       "sample text",
	"col_blob":       "BLOB DATA ONE",
	"col_timestamp":  arrow.Timestamp(time.Date(2023, 1, 1, 12, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_time":       "12:00:00",
	"col_graphic":    "graphic_val",
	"col_vargraphic": "vargraphic_val",
}

var ExpectedUpdatedDB2Data = map[string]interface{}{
	"col_bigint":     int64(12345678901234),
	"col_char":       "c",
	"col_character":  "char_val",
	"col_varchar":    "varchar_val",
	"col_date":       arrow.Timestamp(time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_decimal":    float64(123.45),
	"col_double":     123.456789,
	"col_real":       float32(123.5),
	"col_int":        int64(123),
	"col_smallint":   int32(321),
	"col_clob":       "sample text",
	"col_blob":       "BLOB DATA ONE",
	"col_timestamp":  arrow.Timestamp(time.Date(2023, 1, 1, 12, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_time":       "12:00:00",
	"col_graphic":    "graphic_val",
	"col_vargraphic": "vargraphic_val",
}

var DB2ToDestinationSchema = map[string]string{
	"id":             "integer",
	"col_cursor":     "integer",
	"col_bigint":     "bigint",
	"col_char":       "string",
	"col_character":  "string",
	"col_varchar":    "string",
	"col_date":       "timestamp",
	"col_decimal":    "double",
	"col_double":     "double",
	"col_real":       "float",
	"col_int":        "integer",
	"col_smallint":   "integer",
	"col_clob":       "string",
	"col_blob":       "string",
	"col_timestamp":  "timestamp",
	"col_time":       "string",
	"col_graphic":    "string",
	"col_vargraphic": "string",
}

var UpdatedDB2ToDestinationSchema = map[string]string{
	"id":             "integer",
	"col_cursor":     "integer",
	"col_bigint":     "bigint",
	"col_char":       "string",
	"col_character":  "string",
	"col_varchar":    "string",
	"col_date":       "timestamp",
	"col_decimal":    "double",
	"col_double":     "double",
	"col_real":       "float",
	"col_int":        "bigint",
	"col_smallint":   "integer",
	"col_clob":       "string",
	"col_blob":       "string",
	"col_timestamp":  "timestamp",
	"col_time":       "string",
	"col_graphic":    "string",
	"col_vargraphic": "string",
}
