package db2

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/datazip-inc/olake/tests/testutils"
	"github.com/datazip-inc/olake/tests/testutils/require"
	_ "github.com/ibmdb/go_ibm_db"
	"github.com/jmoiron/sqlx"
)

type seedColumn struct {
	name     string
	datatype string
	value    string
	filtered string
	updated  string
}

func (c seedColumn) definition() string { return c.name + " " + c.datatype }

var seedColumns = []seedColumn{
	{name: "id", datatype: "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", value: "", filtered: "", updated: ""},
	{name: "col_cursor", datatype: "BIGINT", value: "", filtered: "-1", updated: "NULL"},
	{name: "col_bigint", datatype: "BIGINT", value: "12345678901234", filtered: "111111111111111", updated: ""},
	{name: "col_char", datatype: "CHAR(1)", value: "'c'", filtered: "'x'", updated: ""},
	{name: "col_character", datatype: "CHAR(10)", value: "'char_val'", filtered: "'filtered'", updated: ""},
	{name: "col_varchar", datatype: "VARCHAR(50)", value: "'varchar_val'", filtered: "'filtered_val'", updated: ""},
	{name: "col_date", datatype: "DATE", value: "DATE('2023-01-01')", filtered: "DATE('2022-06-15')", updated: ""},
	{name: "col_decimal", datatype: "DECIMAL(10, 2)", value: "123.45", filtered: "50.123", updated: ""},
	{name: "col_decfloat", datatype: "DECFLOAT", value: "123.45", filtered: "50.123", updated: ""},
	{name: "col_double", datatype: "DOUBLE", value: "123.456789", filtered: "50.123", updated: ""},
	{name: "col_real", datatype: "REAL", value: "123.5", filtered: "50.0", updated: ""},
	{name: "col_int", datatype: "INTEGER", value: "123", filtered: "0", updated: ""},
	{name: "col_smallint", datatype: "SMALLINT", value: "123", filtered: "0", updated: "321"},
	{name: "col_bool", datatype: "BOOLEAN", value: "TRUE", filtered: "FALSE", updated: ""},
	{name: "col_clob", datatype: "CLOB(1M)", value: "CLOB('sample text')", filtered: "CLOB('filtered text')", updated: ""},
	{name: "col_blob", datatype: "BLOB(1M)", value: "BLOB(X'424C4F422044415441204F4E45')", filtered: "BLOB(X'00')", updated: ""},
	{name: "col_timestamp", datatype: "TIMESTAMP", value: "TIMESTAMP('2023-01-01-12.00.00.000000')", filtered: "TIMESTAMP('2022-06-15-10.00.00.000000')", updated: "TIMESTAMP('2024-01-01-12.00.00.000000')"},
	{name: "col_time", datatype: "TIME", value: "TIME('12.00.00')", filtered: "TIME('10.00.00')", updated: ""},
	{name: "col_graphic", datatype: "GRAPHIC(11)", value: "GRAPHIC('graphic_val')", filtered: "GRAPHIC('filtered')", updated: ""},
	{name: "col_vargraphic", datatype: "VARGRAPHIC(14)", value: "VARGRAPHIC('vargraphic_val')", filtered: "VARGRAPHIC('filtered')", updated: ""},
	{name: "excludedColumn", datatype: "INT NULL", value: "", filtered: "", updated: "102"},
}

// seedColumnTypes derives every seed column's type tags, excluded ones included, so a data_types
// rule in compatibility_rules.json follows a seed edit with nothing to declare.
func seedColumnTypes() map[string][]string {
	types := make(map[string][]string, len(seedColumns))
	for _, col := range seedColumns {
		types[col.name] = testutils.DataTypeTags(col.datatype)
	}
	return types
}

func filterSeedColumns(t *testing.T, excluded []string) []seedColumn {
	t.Helper()
	names := make([]string, 0, len(seedColumns))
	for _, col := range seedColumns {
		names = append(names, col.name)
	}
	drop, err := testutils.SeedColumnsExcluded(excluded, names)
	require.NoError(t, err, "db2 seed exclusion")

	kept := make([]seedColumn, 0, len(seedColumns))
	for _, col := range seedColumns {
		if !drop[col.name] {
			kept = append(kept, col)
		}
	}
	return kept
}

func createTableQuery(table string, cols []seedColumn) string {
	defs := make([]string, 0, len(cols))
	for _, col := range cols {
		defs = append(defs, col.definition())
	}
	return fmt.Sprintf("CREATE TABLE %s (\n\t%s\n)", table, strings.Join(defs, ",\n\t"))
}

func insertRowQuery(table string, cols []seedColumn, filtered bool, overrides map[string]string) string {
	names := make([]string, 0, len(cols))
	values := make([]string, 0, len(cols))
	for _, col := range cols {
		value := col.value
		if filtered {
			value = col.filtered
		}
		if override, ok := overrides[col.name]; ok {
			value = override
		}
		if value == "" {
			continue
		}
		names = append(names, col.name)
		values = append(values, value)
	}
	return fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s)", table, strings.Join(names, ", "), strings.Join(values, ", "))
}

func updateRowQuery(table string, cols []seedColumn) string {
	sets := make([]string, 0, len(cols)+1)
	for _, col := range cols {
		if col.updated == "" {
			continue
		}
		sets = append(sets, col.name+" = "+col.updated)
	}
	sets = append(sets, "includedColumn = 202")
	return fmt.Sprintf("UPDATE %s SET %s WHERE id = 1", table, strings.Join(sets, ", "))
}

var (
	dbConnsMu sync.Mutex
	dbConns   = map[string]*sqlx.DB{}
)

// buildDSN builds the go_ibm_db DSN from source.json. It mirrors the db2 driver's own DSN
// construction so the tests connect exactly the way the driver does.
func buildDSN(config testutils.SourceConfig) string {
	dsn := fmt.Sprintf(
		"HOSTNAME=%s;PORT=%d;DATABASE=%s;UID=%s;PWD=%s;",
		config.Host("host"),
		config.Int("port"),
		config.String("database"),
		config.String("username"),
		config.String("password"),
	)

	// JDBC-style params if provided
	for key, value := range config.StringMap("jdbc_url_params") {
		dsn += fmt.Sprintf(";%s=%s", key, value)
	}

	// SSL if enabled
	if ssl := config.Sub("ssl"); ssl != nil && ssl.String("mode") != "disable" {
		dsn += ";SECURITY=SSL"
	}

	return dsn
}

func getDB(ctx context.Context, t *testing.T, dsn string) *sqlx.DB {
	t.Helper()

	dbConnsMu.Lock()
	defer dbConnsMu.Unlock()
	if db, ok := dbConns[dsn]; ok {
		return db
	}
	db, err := sqlx.ConnectContext(ctx, "go_ibm_db", dsn)
	require.NoError(t, err, "failed to connect to db2")
	dbConns[dsn] = db
	return db
}

// exec runs one autocommit statement, retrying only the DB2 deadlock victim (SQL0911N,
// SQLSTATE 40001): TestDB2Sync and TestDB22PC run in parallel and their DDL contends
// on the system catalog, so either side can be rolled back and has to replay the statement.
func exec(ctx context.Context, db *sqlx.DB, query string) error {
	var err error
	for attempt := range 3 {
		if _, err = db.ExecContext(ctx, query); err == nil || !strings.Contains(err.Error(), "SQLSTATE=40001") {
			return err
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(time.Duration(attempt+1) * time.Second):
		}
	}
	return err
}

func ExecuteQuery(ctx context.Context, t *testing.T, conf *testutils.TestConfig, operation string) {
	t.Helper()

	dsn := buildDSN(conf.SourceBaseConfig)

	db := getDB(ctx, t, dsn)
	var err error

	integrationTestTable := conf.GetTableName()
	excludedColumns := conf.SeedExcludedColumns
	seedCols := filterSeedColumns(t, excludedColumns)
	var query string

	switch operation {
	case "drop-all":
		query = `
			BEGIN
				FOR t AS SELECT TABNAME FROM SYSCAT.TABLES WHERE TYPE = 'T' AND TABSCHEMA = CURRENT SCHEMA DO
					EXECUTE IMMEDIATE 'DROP TABLE "' || t.TABNAME || '"';
				END FOR;
			END`

	case "create":
		query = createTableQuery(integrationTestTable, seedCols)
		// DB2 has no CREATE TABLE IF NOT EXISTS; tolerate an existing table (SQL0601N,
		// SQLSTATE 42710) to match the other drivers' create semantics.
		if cerr := exec(ctx, db, query); cerr != nil && !strings.Contains(cerr.Error(), "SQL0601N") {
			require.NoError(t, cerr, "Failed to execute create operation")
		}
		requireEmptyTable(ctx, t, db, integrationTestTable, operation)
		return

	case "drop":
		err = exec(ctx, db, fmt.Sprintf(`DROP TABLE %s`, integrationTestTable))
		if err != nil && !strings.Contains(err.Error(), "SQL0204N") {
			require.NoError(t, err, "failed to drop %s", integrationTestTable)
		}
		return

	case "clean":
		query = fmt.Sprintf("DELETE FROM %s", integrationTestTable)

	case "add":
		insertTestData(ctx, t, db, integrationTestTable, excludedColumns)
		require.NoError(t, exec(ctx, db, fmt.Sprintf(`CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE DB2INST1.%s AND INDEXES ALL')`, integrationTestTable)),
			"Failed to populate stats after seeding")
		return

	case "insert":
		err = exec(ctx, db, insertRowQuery(integrationTestTable, seedCols, false,
			map[string]string{"col_cursor": "6", "excludedColumn": "101"}))
		require.NoError(t, err, "Failed to execute %s operation", operation)
		// insert a filtered row — timestamp is before the filter threshold, so it won't be synced
		err = exec(ctx, db, insertRowQuery(integrationTestTable, seedCols, true,
			map[string]string{"excludedColumn": "200"}))
		require.NoError(t, err, "Failed to insert filtered test data row")
		return

	case "insert_2pc":
		query = insertRowQuery(integrationTestTable, seedCols, false,
			map[string]string{"col_cursor": "7"})

	case "update":
		query = updateRowQuery(integrationTestTable, seedCols)

	case "delete":
		query = fmt.Sprintf("DELETE FROM %s WHERE id = 1", integrationTestTable)

	case "evolve-schema":
		evolveQuery := fmt.Sprintf(`ALTER TABLE DB2INST1.%s ALTER COLUMN COL_SMALLINT SET DATA TYPE BIGINT`, integrationTestTable)
		err = exec(ctx, db, evolveQuery)
		require.NoError(t, err, "Failed to execute %s operation", operation)
		// Add new column
		addColumnQuery := fmt.Sprintf(`ALTER TABLE DB2INST1.%s ADD COLUMN includedColumn INTEGER`, integrationTestTable)
		err = exec(ctx, db, addColumnQuery)
		require.NoError(t, err, "Failed to execute %s operation", operation)

		// to clear REORG pending state of DB2 after schema evolution
		query = fmt.Sprintf(`CALL SYSPROC.ADMIN_CMD('REORG TABLE DB2INST1.%s')`, integrationTestTable)

	default:
		t.Fatalf("Unsupported operation: %s", operation)
	}

	err = exec(ctx, db, query)
	require.NoError(t, err, "Failed to execute %s operation", operation)

	if operation == "clean" {
		requireEmptyTable(ctx, t, db, integrationTestTable, operation)
	}
}

// requireEmptyTable fails when a reset left rows behind, at the operation that caused it.
func requireEmptyTable(ctx context.Context, t *testing.T, db *sqlx.DB, table, operation string) {
	t.Helper()
	var rows int
	require.NoError(t, db.GetContext(ctx, &rows, fmt.Sprintf("SELECT COUNT(*) FROM %s", table)),
		"failed to count rows after %s", operation)
	require.Zerof(t, rows, "%s left %d rows in %s", operation, rows, table)
}

func insertTestData(ctx context.Context, t *testing.T, db *sqlx.DB, tableName string, excludedColumns []string) {
	t.Helper()

	seedCols := filterSeedColumns(t, excludedColumns)
	for i := 1; i <= 5; i++ {
		row := map[string]string{"col_cursor": strconv.Itoa(i), "excludedColumn": "100"}
		require.NoError(t, exec(ctx, db, insertRowQuery(tableName, seedCols, false, row)), "Failed to insert test data")
	}
	// insert a filtered row — timestamp is before the filter threshold, so it won't be synced
	filteredRow := map[string]string{
		"excludedColumn": "200",
		"col_date":       "DATE('2021-06-15')",
		"col_decimal":    "500234.123",
		"col_decfloat":   "500234.123",
		"col_double":     "500234.123",
		"col_real":       "500234.0",
		"col_timestamp":  "TIMESTAMP('2021-06-15-10.00.00.000000')",
	}
	require.NoError(t, exec(ctx, db, insertRowQuery(tableName, seedCols, true, filteredRow)), "Failed to insert filtered test data row")
}

var ExpectedDB2Data = map[string]interface{}{
	"col_bigint":     int64(12345678901234),
	"col_char":       "c",
	"col_bool":       true,
	"col_character":  "char_val",
	"col_varchar":    "varchar_val",
	"col_date":       arrow.Timestamp(time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_decimal":    float64(123.45),
	"col_decfloat":   "123.45",
	"col_double":     123.456789,
	"col_real":       float32(123.5),
	"col_int":        int32(123),
	"col_smallint":   int32(123),
	"col_clob":       "sample text",
	"col_blob":       "BLOB DATA ONE",
	"col_timestamp":  arrow.Timestamp(time.Date(2023, 1, 1, 12, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_time":       "12:00:00",
	"col_graphic":    "graphic_val",
	"col_vargraphic": "vargraphic_val",
}

var ExpectedUpdatedDB2Data = map[string]interface{}{
	"col_bigint":     int64(12345678901234),
	"col_char":       "c",
	"col_character":  "char_val",
	"col_bool":       true,
	"col_varchar":    "varchar_val",
	"col_date":       arrow.Timestamp(time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_decimal":    float64(123.45),
	"col_decfloat":   "123.45",
	"col_double":     123.456789,
	"col_real":       float32(123.5),
	"col_int":        int32(123),
	"col_smallint":   int64(321),
	"col_clob":       "sample text",
	"col_blob":       "BLOB DATA ONE",
	"col_timestamp":  arrow.Timestamp(time.Date(2024, 1, 1, 12, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_time":       "12:00:00",
	"col_graphic":    "graphic_val",
	"col_vargraphic": "vargraphic_val",
	"includedcolumn": int32(202),
}

var DB2ToDestinationSchema = map[string]string{
	"id":             "bigint",
	"col_cursor":     "bigint",
	"col_bigint":     "bigint",
	"col_char":       "string",
	"col_character":  "string",
	"col_bool":       "boolean",
	"col_varchar":    "string",
	"col_date":       "timestamp",
	"col_decimal":    "double",
	"col_decfloat":   "string",
	"col_double":     "double",
	"col_real":       "float",
	"col_int":        "integer",
	"col_smallint":   "integer",
	"col_clob":       "string",
	"col_blob":       "string",
	"col_timestamp":  "timestamp",
	"col_time":       "string",
	"col_graphic":    "string",
	"col_vargraphic": "string",
}

var UpdatedDB2ToDestinationSchema = map[string]string{
	"id":             "bigint",
	"col_cursor":     "bigint",
	"col_bigint":     "bigint",
	"col_char":       "string",
	"col_character":  "string",
	"col_bool":       "boolean",
	"col_varchar":    "string",
	"col_date":       "timestamp",
	"col_decimal":    "double",
	"col_decfloat":   "string",
	"col_double":     "double",
	"col_real":       "float",
	"col_int":        "integer",
	"col_smallint":   "bigint",
	"col_clob":       "string",
	"col_blob":       "string",
	"col_timestamp":  "timestamp",
	"col_time":       "string",
	"col_graphic":    "string",
	"col_vargraphic": "string",
	"includedcolumn": "integer",
}
