name: Integration Tests

on:
  push:
    branches:
      - "master"
    paths:
      - '**/*.go'
      - '**/*.java'
  pull_request:
    branches:
      - "*"
    paths:
      - '**/*.go'
      - '**/*.java'

jobs:
  integration-tests:
    uses: ./.github/workflows/integration-tests-runner.yml
    with:
      test_type: integration
