name: Unit Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Install Dependencies
        run: go mod download

      - name: Run All Unit Tests
        run: |
          TEST_PACKAGES=$(git ls-files '*_test.go' | xargs -n1 dirname | sort -u | sed 's#^#./#' | xargs go list -f '{{ .ImportPath }}')
          go test -v -count=1 -skip 'Integration|2PC|Performance' $TEST_PACKAGES
